### ISSUE TITLE
Move editor key bindings to the INI file

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#149]
_From [watusim...@bitfighter.org](https://code.google.com/u/105427273526970468779/) on December 28, 2011 10:17:23_

Put editor key bindings into the INI to allow some customization

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=149_

**Comment by raptor** [comment]
_From [watusim...@bitfighter.org](https://code.google.com/u/105427273526970468779/) on October 07, 2012 14:42:36_

**Labels:** -016a 020

**Comment by raptor** [comment]
_From [bkcon...@gmail.com](https://code.google.com/u/112584966209893525339/) on July 28, 2013 01:36:26_

**Labels:** -Type-Defect Type-Enhancement

**Comment by eykamp** [comment]
This was done long ago, no?
