### ISSUE TITLE
Server Entry Message

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#242]
_From [bobdaduc...@gmail.com](https://code.google.com/u/117749596731898183807/) on September 10, 2013 15:35:23_

Giver server operators an option to set an "entry message" that will display for a player when the player joins the server.  A pop-up window, a private /announcement, or a pm, whatever.  

Welcome to Super-duper-competitive-server!  We have a mumble server at sdfaklsdfasdf.blah

Welcome to the tutorial server!  Join us on the forums or the irc!

Welcome to bobdaduck's Quacky levelgen server!  Go play somewhere else if you want a real game!

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=242_

**Comment by raptor** [comment]
_From [watusim...@bitfighter.org](https://code.google.com/u/105427273526970468779/) on September 15, 2013 12:44:17_

I think this is a great idea.

**Comment by raptor** [comment]
_From [watusim...@bitfighter.org](https://code.google.com/u/105427273526970468779/) on September 15, 2013 12:45:19_

**Labels:** 020

**Comment by raptor** [comment]
_From [bkcon...@gmail.com](https://code.google.com/u/112584966209893525339/) on December 05, 2013 10:11:14_

Mass priority downgrades for long-standing or not immediately important issues.

**Labels:** -Priority-Medium Priority-Low

**Comment by raptor** [comment]
_From [bkcon...@gmail.com](https://code.google.com/u/112584966209893525339/) on December 05, 2013 10:17:33_

**Status:** Accepted

**Comment by raptor** [comment]
_From [Cory.Pou...@gmail.com](https://code.google.com/u/105220164791991617712/) on December 19, 2013 11:44:55_

actually I think this is a good idea can we push this to 19a?

**Comment by eykamp** [comment]
Want to spiff it up a bit, but it is essentially done.

**Comment by raptor** [comment]
I'm not sure this works quite right - I ported this to 019f and the first user to join a server never gets the message.  If another user joins, then the first one gets the message but the second doesn't.

I used a bitfighter server on a different computer to get around local-server weirdness.  Porting to 019f required code changes with the Settings system

**Comment by eykamp** [comment]
Let's reopen and fix if we do another 019x release.  Sorry we didn't get to it for this release.

**Comment by raptor** [comment]
I just tested this on 020 - it seems to work fine.  I don't know why it is acting so funny on 019x

**Comment by raptor** [comment]
ITS WORKING
