### ISSUE TITLE
Move BINDING_OUTGAMECHAT and BINDING_DIAG to new INI section

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#372]
_From [watusim...@bitfighter.org](https://code.google.com/u/105427273526970468779/) on January 21, 2014 01:38:18_

We now have a new key binding section of the INI, for "special keys" like printscreen, that are always active and generally transcend the concept of keyboard/joystick mode.

We should move BINDING_OUTGAMECHAT and BINDING_DIAG into this new section.  Note we'll also have to add a bit of migration code to make sure that the existing bindings are ported when users upgrade.

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=372_

**Comment by raptor** [comment]
_From [watusim...@bitfighter.org](https://code.google.com/u/105427273526970468779/) on January 29, 2014 15:32:04_

No hurry on this... whatever damage has been done won't get worse by waiting.

**Labels:** -019a

**Comment by raptor** [comment]
_From [buckyballreaction](https://code.google.com/u/buckyballreaction/) on July 15, 2015 20:54:51_

It is called BINDING_LOBBYCHAT now.  Also I think the bindings have been completely refactored now.  Did you want all values in the BINDING_TABLE to be in the INI?

**Comment by eykamp** [comment]
Below is a list of keys are not stored in the INI.  Probably adding them would be as simple as changing a false to a true in InputCode.h

BINDING_HELP, BINDING_LOBBYCHAT, BINDING_FPS, BINDING_DIAG, BINDING_LOAD_PRESET_1, BINDING_LOAD_PRESET_2, BINDING_LOAD_PRESET_3, BINDING_SAVE_PRESET_1, BINDING_SAVE_PRESET_2, BINDING_SAVE_PRESET_3

**Comment by eykamp** [comment]
This is now done, will be committed soon.  No migration issues identified.
