### ISSUE TITLE
Add parameter for specifying levelplaylist

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#382]
_From [watusim...@bitfighter.org](https://code.google.com/u/105427273526970468779/) on February 03, 2014 16:07:41_

Add a new option in ParamType enum for specifying a level playlist, and handle it in c2sSetParam()

(Perhaps also add an extra couple of slots for future use without breaking protocol.)

Can't do this until 020 for fear of breaking compatibility

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=382_

**Comment by eykamp** [comment]
Can now specify a new playlist with /setplaylist command.  Will verify that the playlist has at least one file that exists in it, but if that file isn't a valid level, you'll end up playing a pretty boring game
