### ISSUE TITLE
Start script command

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#385]
_From [corteocarl](https://code.google.com/u/corteocarl/) on February 05, 2014 18:52:39_

What new feature or enhancement would you like to request? A nice /startscript \<scriptFile> to start a levelgen in a certain level

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=385_

**Comment by eykamp** [comment]
Done.  /run xxx will be included with 020
