### ISSUE TITLE
Playlist level chooser

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#398]
_From [watusim...@bitfighter.org](https://code.google.com/u/105427273526970468779/) on February 10, 2014 15:00:39_

When playlists are formally released, the level chooser may need to change -- perhaps it should reflect the list-order of the levels rather than the gametype hierarchy we have now.  Also, level list may have repeated levels... 

OTOH, we may conclude that what we've got makes the most sense.  This is mostly a placeholder to remind us to make an explicit decision.

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=398_

**Comment by eykamp** [comment]
Levels are now shown in playlist order when using a playlist
