### ISSUE TITLE
Add notifier in editor when a new player connects

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#405]
_From [watusim...@bitfighter.org](https://code.google.com/u/105427273526970468779/) on February 23, 2014 10:05:37_

Add some sort of subtle (perhaps disablable) notification when a player connects to the editor so people editing know that a potential game situation may be brewing.

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=405_

**Comment by raptor** [comment]
_From [Jomskylark](https://code.google.com/u/Jomskylark/) on February 23, 2014 11:07:48_

Just to be clear: The alert should come when a player connects to the *game - whether it be the editor, the lobby, or a server.

**Comment by raptor** [comment]
_From [watusim...@bitfighter.org](https://code.google.com/u/105427273526970468779/) on February 24, 2014 03:15:51_

Sorry, yes, I was tired and in a hurry when I typed that up.  The notification would happen when a player connected to the master server, in whatever capacity.

**Comment by raptor** [comment]
_From [watusim...@bitfighter.org](https://code.google.com/u/105427273526970468779/) on March 02, 2014 13:29:21_

Will probably require some new m2c methods:
1) m2cSendListOfConnectedPlayers() which gets fired when player first connects to master;
2) m2cPlayerConnected() to send names of new players as they join; and
3) m2cPlayerDisconnected() to send name of players as they quit

For this case, we would probably show an alert or something when (2) was triggered.  But it seems to make sense to add the rest while we're at it

**Comment by raptor** [comment]
_From [buckyballreaction](https://code.google.com/u/buckyballreaction/) on March 08, 2014 17:02:39_

Issue 410 has been merged into this issue.

**Comment by eykamp** [comment]
This is done.  There is a new options menu in the editor that lets you enable/disable this feature.
