### ISSUE TITLE
random bot names

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#432]
_From [watusim...@bitfighter.org](https://code.google.com/u/105427273526970468779/) on June 01, 2014 05:27:59_

Give each bot a random name, so rather than s_bot.1, s_bot.2, we'll have s_bot.sally, s_bot.rachel, etc.

Ideally the bot would be able to control this, but the default behavior should be to give more interesting names.

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=432_

**Comment by raptor** [comment]
_From [buckyballreaction](https://code.google.com/u/buckyballreaction/) on June 03, 2014 21:04:46_

Do we need to preface the bot with 's_bot' ?  We have the 'B' marker on the scoreboard now..

**Comment by raptor** [comment]
_From [watusim...@bitfighter.org](https://code.google.com/u/105427273526970468779/) on June 04, 2014 04:25:45_

I think we need a way to distinguish an s_bot from an eliza_bot... what about:

Lauren (s_bot)
Laura (s_bot)
Deloris (eliza)

**Comment by raptor** [comment]
_From [buckyballreaction](https://code.google.com/u/buckyballreaction/) on June 04, 2014 08:06:39_

I guess that's true...  

I guess I'm thinking that this will be part of my long-envisioned plan to make s_bot into a more versatile bot with profiles or personalities.  If so, it would really be the only bot with so many name changes.  It would be versatile enough to be a completely different bot with each personality and make the 's_bot' part essentially meaningless.

**Comment by raptor** [comment]
_From [corteocarl](https://code.google.com/u/corteocarl/) on September 06, 2014 17:13:54_

I think the random names should be part of the bot.lua, and not the game, since some people might want to have different names etc. S_bot personalities chosen randomly (or by arguments) would be great

**Comment by eykamp** [comment]
I'm thinking the behavior would be in the game as a default, but that when it came time to set the name, the game would call the bot and ask what it wanted.  If the game did not implement the appropriate function, the game would choose.  But yes, the universe of names should be configurable.

**Comment by raptor** [comment]
Done in b53b037d92bdaee9bfcee0e066e83b1cc4fdc597
