### ISSUE TITLE
Show chat history

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#433]
_From [watusim...@bitfighter.org](https://code.google.com/u/105427273526970468779/) on June 01, 2014 05:30:20_

Idea from Lamp:

When entering a chat message (G or L), show the previous chat history as a reference (basically simulate the display the user would have if they hit ctrl+M twice)

It would be nice if this history had some transition animation (we have a class to assist with that), and perhaps it would appear on a slightly translucent background.  Not sure, find something interesting.

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=433_

**Comment by raptor** [comment]
_From [buckyballreaction](https://code.google.com/u/buckyballreaction/) on September 13, 2014 18:35:30_

Should we have this be default?  Or should we have a setting that lets you enable/disable it?

**Comment by raptor** [comment]
_From [watusim...@bitfighter.org](https://code.google.com/u/105427273526970468779/) on September 14, 2014 18:10:57_

I'd say on by default, or always on.  Let's try it with always on, see how it looks, and if it might be annoying we can look for options to disable it.

If this works well, we might be able to get rid of the whole Ctrl+M thing, or at least remove one of the options.

**Comment by eykamp** [comment]
This was done a while back.
