### ISSUE TITLE
Double Tap Boost Buff (Pulse).

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#477]
_From [amginea4...@gmail.com](https://code.google.com/u/118060042413138816983/) on November 07, 2014 19:26:07_

Double Tap boost (Pulse) requires to much energy (100&#37;) and gives too much push. needs a buffer maybe 20&#37; 25&#37; or 33&#37; energy usage and less push given.

see thread http://bitfighter.org/forums/viewtopic.php?f=4&t=2501&p=24672#p24672

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=477_

**Comment by raptor** [comment]
Nah..  seems OK.

**Comment by eykamp** [comment]
Man, I forgot about that!
