### ISSUE TITLE
Lua setScore()

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#480]
_From [corteocarl](https://code.google.com/u/corteocarl/) on November 09, 2014 08:41:51_

What new feature or enhancement would you like to request? A setScore() method. Maybe setScore(team, score) -- score being a number

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=480_

**Comment by raptor** [comment]
_From [buckyballreaction](https://code.google.com/u/buckyballreaction/) on July 04, 2015 09:03:35_

Issue 517 has been merged into this issue.

**Comment by eykamp** [comment]
The idea being to set the current score of the specified team?

**Comment by eykamp** [comment]
Done.  This was a major undertaking.
