### ISSUE TITLE
Would like to be able to check for bots via levelgen

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#489]
_From [erinaare...@gmail.com](https://code.google.com/u/102829777881277243692/) on December 29, 2014 22:24:13_

I understand that there are security risks involved if you let me read/write to files. However, I would like to be able to check if a particular bot code exists within the robots folder.
This would be useful in levels I make that require a specific custom bot. If I could check if it exists, i can default to a normal game when the bot isn't available.

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=489_

**Comment by eykamp** [comment]
In 020 there will be a bf:getBotScripts() command that will return a list of robot scripts.  Use like so:

    scripts = bf:getBotScripts()
    for k,v in pairs(scripts) do 
       print(scripts[k])
    end

Could be easily backported if one were so motiviated.
