### ISSUE TITLE
Prompt before reloading level with CTRL+SHIFT+L

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#501]
_From [buckyballreaction](https://code.google.com/u/buckyballreaction/) on January 22, 2015 22:56:46_
1. Open a level
2. Make lots of changes
3. Try to run a plugin with a CTRL+SHIFT combo and miss-hit the L key

BOOM!, level was reset to last saved state.

I had no idea you could reload the level in this way.  

We must add a prompt before doing it.

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=501_

**Comment by raptor** [comment]
_From [watusim...@bitfighter.org](https://code.google.com/u/105427273526970468779/) on February 08, 2015 01:11:11_

The reason there is no prompt was to make it easier to load levels after editing them in a text editor.  This was once a very important step in level making, but with improvements to the editor over time, may be less so now.  The key combo was chosen when there were no other ctrl-alt options, so as to make it more difficult to do accidentally, given the rather... final... nature of the action.

One possible alternative would be make undo work to undo this action.

**Comment by raptor** [comment]
_From [buckyballreaction](https://code.google.com/u/buckyballreaction/) on May 02, 2015 18:58:32_

Temporary workaround in rdf87de5c6716 .  This just makes it harder to trigger.

**Comment by eykamp** [comment]
This is resolved in 019x, by permitting the user to undo a reload, which seems a more elegant solution than what was proposed.  It turns out to be a fair bit more complex in 020 with our new undo system.  019x is committed, work on 020 is underway.

**Comment by eykamp** [comment]
One scenario we need to consider is that a level is modified outside the editor, removing a team.  The user then reloads the level (Ctrl+Alt+Shift+L), then hits undo.  Any object belonging to the deleted team will now be pointing at a team that does not exist.

**Comment by raptor** [comment]
I don't think we should support outside-editor modifications other than telling people to do so when the level is not loaded.  I remember a few years back that people were clamoring for us to handle special cases with using a text editor while their level was open in the editor - the solution was to support their text-editor action in the editor instead or we would go crazy trying to handle corner cases.

**Comment by eykamp** [comment]
I totally agree, to the extent that things should never crash, and 
that's really what I'm afraid of.  I also realized that we can get into 
the same pickle without reloading the level by:

1. create 2 teams
2. add an item from team 2
3. delete the added item
4. changing the level to 1 team
5. undo the delete

(note I haven't actually tested this, it was just something I was 
mulling over on the way to work)

I think the solution will be to do a team check when undeleting an item, 
and if the team is out of bounds, move it to either team 1 or the 
neutral team.
