### ISSUE TITLE
Quick chat INI issues

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#516]
_From [watusim...@bitfighter.org](https://code.google.com/u/105427273526970468779/) on June 29, 2015 13:29:12_

When INI is missing, or QuickChat section is missing from INI, quick chat messages do not get initialized properly.

See discussion here: http://bitfighter.org/irclogs/index.php?date=2015-06-28

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=516_

**Comment by eykamp** [comment]
I don't believe this ever worked... nonetheless, it has been fixed.
