### ISSUE TITLE
[Lua] Is object on zone?

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#519]
_From [corteocarl](https://code.google.com/u/corteocarl/) on July 01, 2015 21:26:27_

What new feature or enhancement would you like to request? A BFObject:isOnZone(zone) or similar would be useful! The events onShipEnteredZone() is great, but this would be a nice addition too.

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=519_

**Comment by eykamp** [comment]
This would probably be a MoveObject rather than a BFObject... after all, no need to check if a loadout zone has entered a goal zone... is there?

**Comment by eykamp** [comment]
Since a ship is a MoveObject, do we still keep the Ship::isOnZone method?  Fire both for a ship, or only one?

**Comment by eykamp** [comment]
Done.  When implementing it became clear how this "wants" to work... Ships do not trigger onObjectEnteredZone, but other MoveObjects do.

Can test with this script:
```Lua
function onShipEnteredZone(ship, zone)
	levelgen:announce("ship entered zone!")
end

function onShipLeftZone(ship, zone)
	levelgen:announce("ship left zone! ")
end	

function onObjectEnteredZone(obj, zone)
	levelgen:announce("obj entered zone!")
end	

function onObjectLeftZone(obj, zone)
	levelgen:announce("obj left zone!")
end	


function main()
	bf:subscribe(Event.ShipEnteredZone)
	bf:subscribe(Event.ShipLeftZone)
	bf:subscribe(Event.ObjectEnteredZone)
	bf:subscribe(Event.ObjectLeftZone)
end
```

**Comment by eykamp** [comment]
Done
