### ISSUE TITLE
Option to default to old loadout behavior

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#523]
_From [buckyballreaction](https://code.google.com/u/buckyballreaction/) on July 03, 2015 22:26:04_

Provide option for clients to reset to default loadout when respawning (old behavior) instead of keeping last weapon active.

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=523_

**Comment by raptor** [comment]
_From [buckyballreaction](https://code.google.com/u/buckyballreaction/) on July 03, 2015 21:26:22_

Maybe could be combined with issue #146

**Comment by raptor** [comment]
Closing because it's old and I don't understand the issue anymore

**Comment by eykamp** [comment]
I think I understand it, but it's probably not worth the added complexity.
