### ISSUE TITLE
CoreItem does not work in Rabbit

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#526]
_From [mtmac...@owu.edu](https://code.google.com/u/100379094766182887248/) on July 16, 2015 10:46:34_

What steps will reproduce the problem? 1. Add a CoreItem to a Rabbit game type
2. Play map to completion 
3. Try to restart the map. 

What is the expected output?
The map should play as well as it did the first time.

What do you see instead?
Ships spawn on top of each other in infinite space, no teams, no barriers

What version of the product are you using? 
19e? The most recent (7/16/2015)

On what operating system?
Windows 7

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=526_

**Comment by raptor** [comment]
_From [buckyballreaction](https://code.google.com/u/buckyballreaction/) on July 16, 2015 10:04:14_

Hi,

Would you be willing to post the map here for me to test this?  It can be included in a zip file.

Thanks!

**Comment by raptor** [comment]
_From [buckyballreaction](https://code.google.com/u/buckyballreaction/) on July 23, 2015 22:14:37_

I attempted to duplicate this but I cannot seem to.  Could you please send the original map that caused this?  Or, are there more details you can give me such as how many teams, how many cores, etc.

Thanks!

**Comment by eykamp** [comment]
I cannot duplicate either.  I'm going to close this until we get more info.
