### ISSUE TITLE
Sdd healing icon next to people who have repair

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#528]
_From [Embergam...@gmail.com](https://code.google.com/u/115112513480272962705/) on August 06, 2015 22:41:28_

It would be helpful to show which players have repair so teammates will know they can get healing. Use a small version of the repair icon next to the players name. 

Only visible to teammates.

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=528_

**Comment by raptor** [comment]
_From [watusim...@bitfighter.org](https://code.google.com/u/105427273526970468779/) on August 06, 2015 21:43:08_

**Labels:** 020 gci

**Comment by eykamp** [comment]
Done!  (Could be backported to 019x)
