### ISSUE TITLE
Spy bug buffs

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#529]
_From [watusim...@bitfighter.org](https://code.google.com/u/105427273526970468779/) on August 06, 2015 22:52:17_

Give spy bugs greater range and/or make them harder to kill.

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=529_

**Comment by Xelor41023** [comment]
Actually I think a severely lower energy usage would be better maybe have 5-7 uses before they wear out.

**Comment by Xelor41023** [comment]
This Seems silly but can we give Spy bugs a Circle instead of  a rectangle of range?

**Comment by eykamp** [comment]
It would be possible, but require a little more computation, and would 
it really offer any benefit in terms of fun?

**Comment by Xelor41023** [comment]
I think so  It would allow for spy bugs to be more usable in real game situations since all maps are not horizontal some are more vertical and would allow for better guarding of key points in maps.

**Comment by eykamp** [comment]
Maybe a hexagon would look cooler than a circle.  Then we could reshape 
the spybug in-game as a tiny hexagon, which might also be cool.

**Comment by Xelor41023** [comment]
Hexagons would still favor horizontal and vertical  but not diagonal but circles would give equal footing but in a game like bitfighter would this matter?

**Comment by raptor** [comment]
I like hexagons - it's a good compromise between aesthetics and computation requirements.

**Comment by raptor** [comment]
Hexagons are done in both 019f and 020
