### ISSUE TITLE
Gles 0.19e SDL2 build black screen

### ISSUE THREAD

**Issue by petevine** [bitfighter/bitfighter#530]
Hi, 

I've managed to build a gles bitfighter on my odroid C1 but upon starting the game all I get is black screen (and music playing in the background).
Any hints on how to debug this problem?

**Comment by raptor** [comment]
Hi, I last build version 019c for a RPi and it ran OK - I hadn't heard of the ODROID until you mentioned it.  

I have a hunch that maybe something is wrong with the truetype fonts.  If you rename the 'fonts' subdirectory so it doesn't load the TTF fonts (and fallback to the old vector fonts, which may be distorted), do you see the menus?

Thanks!

**Comment by raptor** [comment]
Looking into the specs of the odroid, the video hardware says it's GLES 2 compatible.  Does this suggest that GLES 1 is only available in software?  

If so, then it may be that those libraries are missing/disabled somehow.

**Comment by petevine** [comment]
Removing the fonts didn't help. 
GLES is supported up to v2.

BTW there's a problem in X with displaying the alpha channel due to the way the Mali chip does it internally - normally it's solved by going below 32bpp if an app doesn't set it correctly.
I've tried that and there's no difference @16bpp.

**Comment by petevine** [comment]
I've just tried to build an SDL version:

[ 79%] Building CXX object zap/CMakeFiles/bitfighter_client.dir/NexusGame.cpp.o
In file included from /home/odroid/bitfighter-019e/zap/NexusGame.cpp:16:0:
/home/odroid/bitfighter-019e/zap/OpenglUtils.h:17:28: fatal error: SDL_opengles.h: No such file or directory
 #  include "SDL_opengles.h"
                            ^
I think this include might be openpandora specific as the only SDL_opengles.h I've got is located in include/SDL2. For SDL there's just SDL_opengl.h

**Comment by raptor** [comment]
Good find - I think it is highly possible that the SDL2 compiled for that platform does not have GLES 1 support compiled in.  You may have to compile it yourself if it is even possible.

I'm glad you eventually got it working.  We were thinking of removing SDL1.2 support completely this next release, but maybe that should be delayed until we get GLES2 support compiled in.

**Comment by petevine** [comment]
Oops, we have a misunderstanding - I'd already tested my manually compiled version of the SDL2 library (gles-only) and it works fine in ufoai (gles1) or caveexpress(gles2).
It doesn't work here and the result of building bitf with/without GLES was exactly the same (SDL2) which I find somewhat suspicious as it probably should crash.
Is there a way to get more verbosity?

**Comment by raptor** [comment]
Ah OK.  I just checked out the SDL source code and looked - SDL_opengles.h is a standard header.  Is it possible it is not found on your include path for some reason?

**Comment by petevine** [comment]
You mean it's included in SDL1??

**Comment by raptor** [comment]
Oh no - I meant SDL2.  I used 'SDL' for the source code repository name, the newest revision of which is the SDL2 branch.

**Comment by petevine** [comment]
Oh, that's more like it :) I've got a fully functional SDL2 library with all includes in the right places. 

To recap:
    The game builds and runs fine with SDL1/soft OpenGL
    It also builds with SDL2/GLES but doesn't display anything.

Is there a switch or a compile time option to see some debug messages?

**Comment by raptor** [comment]
If you're using 'make' after CMake, then you can do:  `make VERBOSE=1` which will show a lot of noise!

**Comment by petevine** [comment]
I meant targeting the runtime but this one could prove useful as well.

**Comment by raptor** [comment]
The next step is full debugging of Bitfighter (if it is a Bitfighter issue):

Compile with the flag, `-g`.  This can be done by re-running CMake like so:  `cmake -DCMAKE_BUILD_TYPE=Debug ..`.  And then `make`...  Then you can step through code to see what is happening.  This is probably too extreme for what you want to do.

If the issue is not the fonts, then I suspect the issue is either something with your system set-up (hardware/libraries/etc.) or with how Bitfighter is initializing the GL context.  If it is Bitfighter's fault, more research will be required as I do not have an odroid.

**Comment by petevine** [comment]
This is the warning I was referring to:

/home/odroid/bitfighter-019e/fontstash/fontstash.c: In function ‘sth_add_font’:
/home/odroid/bitfighter-019e/fontstash/fontstash.c:259:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(data, 1, datasize, fp);

**Comment by eykamp** [comment]
Do you get the same warning if you remove the fonts folder?

**Comment by petevine** [comment]
It's a compiler warning, not a message from a running binary!

**Comment by raptor** [comment]
That warning is (mostly) harmless; see here:  https://stackoverflow.com/questions/7271939/declared-with-attribute-warn-unused-result

Although you replace that line with something like:

    if(fread(data, 1, datasize, fp) != datasize)
        printf("file reading error\n");

This would print out if there was an error reading the fonts.  But that's if the fonts are a problem in the first place - since you have tried removing the fonts directory then I don't think fontstash (i.e. the TTF fonts) are a problem.

I think the larger problem has something to do with OpenGL on your system but I'm not sure where to go from here.  I have to research a little...

**Comment by petevine** [comment]
Forgot to ask - when originally ported to gles the game wasn't using SDL1 by any chance? (the way ufoai did)
If not maybe I might try the revision you mentioned - is there a snapshot somewhere?

**Comment by raptor** [comment]
No, when compiling with the CMake flag `-DUSE_GLES=1` it requires SDL2.  We maintain the ability to use both SDL1.2 and SDL2, but only SDL2 was OK for GLES

**Comment by petevine** [comment]
Re debugging - if you could provide the necessary breakpoints for gdb I could build the debug version and send back the info. Then we could have a few answers even without you getting an odroid ;)
Or you could try setting up the mesa versions of EGL and GLES on x86 to see if it's working for you there.

**Comment by raptor** [comment]
I duplicated this with Mesa libGLESv1_CM on my x86_64 openSUSE box.  I got a black screen with music, just like you - I'll have to dig a little deeper.

**Comment by raptor** [comment]
Well, I went through many, many OpenGL calls to try and debug this, but got no further.  I went through much of this, too:
http://retokoradi.com/2014/04/21/opengl-why-is-your-code-producing-a-black-window/
This may have to wait until we can finish our GLES2 abstraction layer.

**Comment by petevine** [comment]
Yeah, but did you eliminate the really silly stuff, like the renderer never being used at all?
I find it strange I got the very same result with an opengl version of bitfighter coming from SDL2 that doesn't even have opengl compiled in.

**Comment by raptor** [comment]
I think SDL2 is failing to get a proper GLES 1 context.  What version of SDL are you using on the odroid?

**Comment by raptor** [comment]
One other thing.  If you add the following code after the line with `SDL_GL_CreateContext` in VideoSystem.cpp, what does it print out when you start the game?:
```
   const GLubyte* ver = glGetString(GL_VERSION);
   if(ver) printf("%s\n", ver);
   else printf("no GL_VERSION\n");
```

**Comment by petevine** [comment]
I've tried the stable SDL 2.0.3 as well as the latest checkout.

It's OpenGL ES 2.0! In case you're wondering how that's possible -lGLES_CM -lEGL is equivalent (symlinks) to -lMali which also houses GLES2.

**Comment by raptor** [comment]
Are you saying that that code printed out "OpenGL ES 2.0"?  I'm interested in the exact string that it prints out because SDL should be able to get an ES 1.0 or ES 2.0 context.

Another thing you can try is to add the following lines in VideoSystem.cpp before the `SDL_CreateWindow` call:
```
#  ifdef BF_USE_GLES
   SDL_SetHint(SDL_HINT_RENDER_DRIVER, "opengles");
   SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 1);
   SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 1);
   SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
#  endif
```
Then see what the `glGetString(GL_VERSION)` I mentioned before prints out.

Thanks for help so far!

**Comment by petevine** [comment]
Yes, it used "OpenGL ES 2.0" before, now it's all been fixed!
Thx

**Comment by raptor** [comment]
Wait wait!  Are you saying that those `SDL_GL_SetAttribute` lines above fixed it?  If so, then I'll commit that change.

**Comment by petevine** [comment]
That's exactly what happened! Now the correct render is picked.

Btw, is the following normal or the installation is broken?

````Error compiling script /home/odroid/.bitfighter/scripts/luavec.lua
````cannot open /home/odroid/.bitfighter/scripts/luavec.lua: No such file or directory

**Comment by raptor** [comment]
OK Good.

Yeah, it looks like the installation is broken somehow...  you can fix it by copying the luavec.lua script from the installation tree in `/usr`  to your user prefs directory at `/home/odroid/.bitfighter/scripts/`

I bet it happened if you installed 019c after 019e.  The proper fix would be to reinstall 019e and remove the whole folder `/home/odroid/.bitfighter/` and let it rebuild on the first run of 019e again.  Let me know if you run into more trouble.

Thanks again!

**Comment by petevine** [comment]
Yes, I tried 019c in between.
That'll probably be it as far as I'm concerned as the game seems to be running perfectly well.

Cheers!
