### ISSUE TITLE
GLES 0.19e high cpu usage (Odroid C1)

### ISSUE THREAD

**Issue by petevine** [bitfighter/bitfighter#532]
Even though it might be perfectly normal on arm processors, simply displaying the welcome screen consumes 60% of a 1.7GHz core. (using a fully accelerated Mali gpu). The only glesv1 app I can compare bitfighter with, namely ufoai, is using about 30% in similar cicumstances so maybe there's something to it.

Have a look at these attached callgrind annotations in case there's an issue with drawing the screen.

**Comment by petevine** [comment]
Just images allowed? Here's a link then:

https://gist.github.com/petevine/756378dee06f0da6a0ee

**Comment by raptor** [comment]
Hi,  could you please provide the original callgrind.out file?

Thanks!

**Comment by petevine** [comment]
https://gist.github.com/petevine/00ec953f5972e42e5573

In case your viewer complains about the last line that got truncated:

totals: 3247875599

**Comment by eykamp** [comment]
When you say "welcome screen" do you mean the screen where you enter your name/pw, or the main screen where the Bitfighter logo is displayed?

**Comment by petevine** [comment]
The first menu screen with 'play', 'nickname' and so on.
It could be related: the mouse pointer is flickering if it's not positioned over one of the menu options.

**Comment by raptor** [comment]
Thanks for the callgrind output.  

I know this is crazy, but it looks like 1/4 to 1/2 of the graph calls have to do with vorbis decoding.  Could you check performance again with the music set it to zero?

If it is indeed vorbis decoding, than I suspect that the libvorbis that is compiled on the system has something very wrong with it - like it is a floating point variant running on a chip without an FPU.

**Comment by petevine** [comment]
Nope, it made virtually no difference. (stopped pulseaudio to be absolutely sure)

**Comment by raptor** [comment]
Sorry, when I meant 'music set to zero' I meant in the game itself, under the options menu.  

If you set all the sounds to zero, and it still makes no difference, could you please get a new callgrind report on the menu with the sounds off?

Thanks again!

**Comment by petevine** [comment]
Sure, check this post again in a few minutes.

**Comment by petevine** [comment]
I'm new to Arm platforms so please don't waste too much time on this. Once I get a better impression of the board's gpu/X11/Mali performance I'll let you know if it was right to expect more.

**Comment by raptor** [comment]
The new callgraph basically shows most of the larger, remaining calls are to the GLES layer.  I suspect that the board uses a GLES 1 abstraction layer.  This, combined with the fact that our code doesn't use (vertex) buffer objects, probably means that performance will be high with the CPU.

I'm not sure there's much we can do other than get to work on the GLES 2 layer

**Comment by petevine** [comment]
I've compared it to an x86 machine (2Ghz, single core Athlon) with OpenGL 1.4 and it's using just 5% on a gpu (Geforce FX5200) that's probably similar or weaker than the Mali chip. Is that expected?

I can supply the callgrind output if you wish.

**Comment by petevine** [comment]
I've just discovered even a sokoban game written in Rust that is merely using SDL2/SDL2_image is exhibiting the exact same behaviour. So it's down to SDL and not related to any GL stuff.

**Comment by raptor** [comment]
Thanks for testing further.

**Comment by petevine** [comment]
The sokoban-rs was constantly redrawing the screen (polling for events instead of waiting for an event) so it was broken after all.
Back to square one :)

**Comment by petevine** [comment]
I've done something rather funny just now - it seems running the regular OpenGL bitfighter via the glshim wrapper produces the exact same performance/cpu usage :)

**Comment by eykamp** [comment]
Bitfighter does this as well.

**Comment by petevine** [comment]
In the case of sokoban-rs you only need to render once and wait for user input. Bitfighter has these dynamic menus so it probably needs to do it this way, doesn't it?

**Comment by eykamp** [comment]
My understanding is that is the way SDL works; it's also the way GLUT works, which is the graphics framework that Bitfighter was originally developed with. 

If the cpu issue is related to re-rendering, you will probably see this with every SDL game out there.
