### ISSUE TITLE
Eliminate glPushMatrix and glPopMatrix

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#533]
Needed for GLES2 support

**Comment by raptor** [comment]
Found some likely useful info on how to do this:
http://stackoverflow.com/questions/13647108/matrix-stacks-in-opengl-deprecated

**Comment by raptor** [comment]
GLM looks like it provides all the matrix thingies we need:
https://github.com/g-truc/glm

**Comment by raptor** [comment]
Moved to issue #619
