### ISSUE TITLE
Review all levelgens in Pleiades and fix ones that pass tables to bf:findAllObjects

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#536]
Subway is a levelgen that still passes an empty table to bf:findAllObjects() call, which was deprecated in 019x, and will be an error in 020.  This should be fixed on Pleiades, and other levelgens should be reviewed for the same.

See #584

**Comment by fordcars** [comment]
I am not getting a deprecation error on 019e. I didn't know it was deprecated!

**Comment by eykamp** [comment]
Opened #584 to add the deprecation warning for 019f.

**Comment by raptor** [comment]
Was the reason for removing this because of performance alone?  I don't remember the history...

**Comment by eykamp** [comment]
The reason for removing it is that it's confusing.  We added it for performance reasons, but then when you ported to luac, it proved unnecessary, and a decision was made (by me? us?) to remove it.  At least that's how I remember it.

**Comment by raptor** [comment]
Also fix ones with deprecated calls like `getLoc` to use `getPos`, etc. (Recently discovered this due to issue #662 )

**Comment by raptor** [comment]
Fixed all I could find of:
* getLoc/setLoc
* getTeamIndx
* findAllObjects* with empty table as first arg
