### ISSUE TITLE
Global Moderation System

### ISSUE THREAD

**Issue by Xelor41023** [bitfighter/bitfighter#537]
Implement a global moderation system over the member based one into bitfighter and move most game commands there this is important preparation for when bitfighter should get on as if the player count increases they will be a high abuse curb so reserve most commands for global moderaters and admins.

**Comment by raptor** [comment]
Bitfighter is server-based with owners owning their own servers.  We do not take control from server owners.  We have several moderator tools available for server owners.

**Comment by Xelor41023** [comment]
However with a higher player count there will be a high abuse curb from members who will needlessly kick players just to be hateful and  rude or have a unfair advantage to other players It would be important for bitfighters expansion to have a more stable less volatile system.

**Comment by fordcars** [comment]
I guess that maybe at some point the Master Server could ban IPs, but for now maybe it isn't necessary?

**Comment by Xelor41023** [comment]
Maybe Mac address banns + IP + username bans 

It would make the game more balance players  would be stacking teams or kicking the "pro" players out or changing there username to be rude..... Almost every game I have seen with a player based moderation system has failed.

**Comment by raptor** [comment]
If a server owner is abusive, there is nothing that we can do - they own the server.   

As for banning IPs on the master server, few people have static IPs to which this would be very useful.  Also, they could always just directly connect to any server they want with the `/connect` command.

Bitfighter is *not* a central-controlling game and it can never be one.  It is open source and easily editable.
