### ISSUE TITLE
Balance Armor

### ISSUE THREAD

**Issue by Xelor41023** [bitfighter/bitfighter#538]
Armor + Repair is overpowered Balance it out some more maybe bring back bouncer weakness

**Comment by raptor** [comment]
Armor was balanced to be better than before.  The bouncer weakness was removed on purpose because it added complexity that few people grasped.

Any other suggestions to balance it?  Maybe making repair repair slower?

**Comment by Xelor41023** [comment]
Not sure I think a double tap repair for full heal but at the cost of 100% energy would be fine it would leave them open.

Generally repair is broken on armor but inferior to everything else.

**Comment by eykamp** [comment]
I think this discussion belongs on the forums.
