### ISSUE TITLE
Give Forcefields a Health Gauge.

### ISSUE THREAD

**Issue by Xelor41023** [bitfighter/bitfighter#546]
Give force fields a "health gauge" so players know If they need to be repaired or how much damage is left to negate them.

Perhaps have the forcefield "fade" as it takes more damage. Or have it have a Health bar on the forcefields emitter.

**Comment by NothingMuchHereToSay** [comment]
So basically a "fade". I can dig this. +1

**Comment by raptor** [comment]
Forcefields already fade when you move over them (if it's your color).  

How would you suggest we make the health fade different from that?

**Comment by Quartz-the-Magnificent** [comment]
If forcefields had a very small health bar, like turrets but even smaller, that would be fantastic. I concur.

**Comment by bobdaduck** [comment]
Make the force field beam itself fade to black for every 10% of life it loses.

**Comment by raptor** [comment]
Fixed with several revisions ending in b0a45f934fa80923bb47318f0eb7a95afc0d62fb
