### ISSUE TITLE
Level vote bug.

### ISSUE THREAD

**Issue by Xelor41023** [bitfighter/bitfighter#547]
Setup.

1. Have a levels timer be less then 30 seconds.
2. Have a level reset vote occur  at about 20 seconds (which is defaulted to 30 seconds.)
3. Level will end and go to new level while vote is still persistent.
4. Reset vote will end on the new level.
5. It will reset again to the new level not the old one.

Expected result : Should reset to the old level not the new one.
System : windows 10 32 bit
Build : 19E

**Comment by NothingMuchHereToSay** [comment]
I remember testing this I think, confirmed.
