### ISSUE TITLE
Kickbots Crash

### ISSUE THREAD

**Issue by Xelor41023** [bitfighter/bitfighter#549]
Adding 255 bots then kicking them all can crash the game.

Stack trace here http://pastie.org/10481867

Done on testing build 10575/020

**Comment by raptor** [comment]
What version of Bitfighter is this?  Also, does this crash the game, or just the Lua system?

**Comment by raptor** [comment]
Oops, I see it is 020.  Bots are broke on 020.  But is this a hard crash where the game completely closes?

**Comment by Xelor41023** [comment]
It completely crashes the game and has to be restarted.

**Comment by raptor** [comment]
experimental_020 branch has been relegated to history, including its bugs.
