### ISSUE TITLE
Armor and repair is an unbeatable combo

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#551]
Reduce efficiency of repair when you have armor, so that it either consumes more energy, repairs less, or something else.

**Comment by TheSkybax** [comment]
It was suggested that Repair should repair a certain number of "points" per second rather than a percentage of total health. This would make repair the same usefulness regardless of how much health you have

**Comment by raptor** [comment]
Fixed in commit 04b5109
