### ISSUE TITLE
In-game server messages aren't disappearing any more

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#552]
This screenshot shows this issue.  These messages just stay there and don't time out.
![screenshot_0](https://cloud.githubusercontent.com/assets/6452412/10870133/3c2b0650-8080-11e5-9d56-d47f1f9c3cf9.png)

**Comment by raptor** [comment]
watusimoto, did you fix this recently?

**Comment by eykamp** [comment]
I believe so.  I'll verify later and close this case.  I didn't know it was here.
