### ISSUE TITLE
Make health bar have minimum luminosity

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#554]
Can dark ships have grey health so that people can actually see it?

Not all ships, I like how it's the color of the ship typically, but particularly for pitch black ships, it would be nice.

--> Could solve by converting ship color to HSL using this code http://stackoverflow.com/questions/3018313/algorithm-to-convert-rgb-to-hsv-and-hsv-to-rgb-in-range-0-255-for-both , then ensure minimum L, then convert back to RGB.

Probably more work than benefit, but could be a fun little task.

**Comment by raptor** [comment]
I wrote a python script once to toy with 'acceptable' HSV changes to colors as a way to calculate a color from user names in-game:

https://gist.github.com/raptor/d9fe21dd34ab56a45123

Basically this will not allow a saturation or value below a certain amount, thus guaranteeing a brighter color.  Maybe it'll be useful for this, too.

**Comment by eykamp** [comment]
This was done in both 019x and 020.
