### ISSUE TITLE
Support for gcc5

### ISSUE THREAD

**Issue by susnux** [bitfighter/bitfighter#556]
Gcc5 is out for a while, it would be nice to add support for it.
At the moment it throws: 

    tnl/tnlTypes.h:337:8: error: #error "TNL: Unsupported version of GCC (see tnlMethodDispatch.cpp)"
    #      error "TNL: Unsupported version of GCC (see tnlMethodDispatch.cpp)"
             ^

**Comment by raptor** [comment]
Hi and thank you!

It is fixed in master now:  637d46fba05164b8b5580841077e94f08a22cf7d

Please reopen this if you run into other issues - Bitfighter hasn't been compiled with GCC 5 before.

**Comment by susnux** [comment]
Thank you
