### ISSUE TITLE
Update Pleiades server when new levels are added to databaes

### ISSUE THREAD

**Issue by ianeyk** [bitfighter/bitfighter#557]
So we can play new levels immediately rather than waiting for someone to update the server manually.

**Comment by raptor** [comment]
A partial fix for this has been implemented with adding a 'pleiades updates' server that does the latest maps. It still only syncs once a day.

The process that does this works like this:

1. Scan level database
2. Dump new levels to 'levels' folder
3. Restart server

I think this is sufficient but I'm open to other changes. If instant updates are wanted, then hosting your own server is probably the best way to go about it.
