### ISSUE TITLE
Crash on level load

### ISSUE THREAD

**Issue by bobdaduck** [bitfighter/bitfighter#563]
This level crashes when I switch to it in-game.  I don't know why.  I don't know what's in it.  I just wanted you to know that I know.
[Beater crash.zip](https://github.com/bitfighter/bitfighter/files/241821/Beater.crash.zip)

**Comment by raptor** [comment]
The levelgen script has a bug.  I think it crashes because of issue #588.

Are you running Bitfighter 32-bit on Windows 10 64-bit?

**Comment by raptor** [comment]
This was fixed with #588.
