### ISSUE TITLE
Add onShipEnteredZone event for robots

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#564]
Robots entering zones don't trigger onShipEnteredZone.  To fix, need to add the zone checking code from ship::idle() to robot::idle().

**Comment by raptor** [comment]
This used to work.  And I think it still should:  `Robot::idle()` calls `Ship::idle()` on the server, which calls `Ship::checkForZones()`.

**Comment by eykamp** [comment]
If that call still occurs (which I didn't check for), then it should still work.  The first step needs to be to verify that this is, in fact, broken.

**Comment by raptor** [comment]
I suspect the issue is with the Lua script.  Note that the object type returned for a robot is ObjType.Robot instead of ObjType.Ship

**Comment by raptor** [comment]
Fixed in 922094f
