### ISSUE TITLE
Fix enum display on the luadocs

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#566]
See: http://bitfighter.org/luadocs/

Enums are all buggered up.  Looks like it might be the output from line 357 of luadoc.pl.  It also looks like doxygen isn't doing something it used to do, or something.  Not sure.

Be aware that when regenerating the docs, there may be items for 020 in there that are not ready for the 019x docs (the thing that comes to mind are the two new events: ObjectEnteredZoneEvent and ObjectLeftZoneEvent).

**Comment by raptor** [comment]
Turns out this is because doxygen 1.8+ is required, but we had 1.6.1 installed on the server. I have removed version 1.6.1 and manually installed 1.8.3 into the system path at /usr/local/bin. 

Lua docs are update, too.
