### ISSUE TITLE
Loading Preset Loadout Does Not Show  Message.

### ISSUE THREAD

**Issue by Xelor41023** [bitfighter/bitfighter#567]
Message does not load as it should.
1. Create a Loadout press Ctrl+1 to save the loadout message saved shows ups.
2. Press Alt +1 to load the preset  loadout before touching a loadout zone  no message occurs.

Expected the old message saying the loadout was loaded  and to touch a loadout zone to accept the changes.

Build  10572/19e

OS Windows 10 32bit.

**Comment by eykamp** [comment]
Fixed.
