### ISSUE TITLE
Allow Distance Control on Shots.

### ISSUE THREAD

**Issue by Xelor41023** [bitfighter/bitfighter#568]
Instead of having shots go a fixed distance and having velocity extend the range of shots I think it would be good to have a option to have shots to only go the distance you are aiming your cursor Within the max range for a weapon this setting would be "Advanced" the original would be "Basic" 

This would allow for more competitive play with weapons but still allow casual players to play more casually.

**Comment by eykamp** [comment]
This should be discussed on the forum.  Probably opposed due to complexity, failure to work with controllers, and dubious value.

**Comment by Xelor41023** [comment]
For controllers the left stick could control  orientation/ movement and the right stick could control the cursor.

the main reason being For weapons like burst and seeker being able to control how far they go before they burst or turn would greatly help. like being able to burst someone near a corner.
