### ISSUE TITLE
Download from Pleiades broken

### ISSUE THREAD

**Issue by ianeyk** [bitfighter/bitfighter#569]
When I download Rounded Soccer level using the in-game download command 

`/dlmap zemmer_rounded_soccer`

the game type is changed from soccer to bitmatch; time and score to win are also corrupted.

**Comment by raptor** [comment]
Hi,

Does this happen with this map only, or other maps, too?

Also, are you on the release version of Bitfighter (019e) or some other version?

**Comment by ianeyk** [comment]
It's 019e, haven't checked other levels. But I do know that when you download the level on a zip file, it is a soccer level.

On Feb 9, 2017 9:25 PM, raptor <notifications@github.com> wrote:

Hi,

Does this happen with this map only, or other maps, too?

Also, are you on the release version of Bitfighter (019e) or some other version?

**Comment by raptor** [comment]
I just tested this in 019f and it looks like it is gone.
