### ISSUE TITLE
Opening levels in the level editor open with the wrong filename, leading to overwriting of existing levels when you save.

### ISSUE THREAD

**Issue by bobdaduck** [bitfighter/bitfighter#570]
If I open "wub.level" and then quit to the main menu, then open a different level, the filename shown in the F2 menu is "wub.level", and if I save I will overwrite it.

**Comment by raptor** [comment]
Duplicate of #560?

**Comment by eykamp** [comment]
Maybe yes.  Let's leave them both open, and when we fix this one, we 
should check to see if it fixes #560.  I'll put a note in that one as 
well in case it gets tackled first.

**Comment by bobdaduck** [comment]
Oops, yes, duplicate.  I didn't remember filing it already.  Bitfighter party tonight?
