### ISSUE TITLE
Make sure game can handle BotNavMeshZone objects

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#571]
Crash on the the level CloseQuarters:   Unknown object type "BotNavMeshZone" in level "~/dedicated_servers/partyserver/levels/downloaded_CloseQuarters.level"

BotNavMeshZone is an artifact from a bygone era -- the level parser should ignore these objects, and not issue warnings or crash (or, maybe, issue a very wee warning).  Verify that levels, such as CloseQuarters load properly.

**Comment by raptor** [comment]
This did not cause a hard crash.  It was only an artifact of looking at the server logs.  We only had one hard crash during the night and it was about 6 minutes into a level called 'Rounded HTF' (which we were about to win!)

**Comment by eykamp** [comment]
Ah, ok.  I misunderstood the IRC logs.  These are easy cases to deal with!  I thought we handled this situation already, so I was surprised.

**Comment by eykamp** [comment]
But did the level have any problems aside from an emitted warning about the BotNavMeshZone?

**Comment by raptor** [comment]
Nope.  

Maybe instead of dumping out 40 lines of 'Unknown object type "BotNavMeshZone"' we only need to dump out one line.

**Comment by eykamp** [comment]
Yes, ok.  I'll create a new case for that.
