### ISSUE TITLE
Investigate crash from Carnival

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#572]
Take a look at this level, and see if there is a bug that caused this crash.  In any event, a lua scripting problem should not bring the game down.

Loading Levelgen Carnival [levelfile "Carnival.level"]... Done. [2017-02-11 Sat 23:07:18]
***LEVELGEN ERROR***
In method onTick():
~/dedicated_servers/partyserver/levels/Carnival.levelgen:235: attempt to index a nil value
Stack Traceback
===============
(1) Lua global 'doSammy' at file '~/dedicated_servers/partyserver/levels/Carnival.levelgen:235'
        Local variables:
         zone = userdata: 0x4039aba0
         speed = userdata: 0x4039abd0
         loc = point (-1058.3033447266,1280.5748291016)  {y:1280.5748291016, x:-1058.3033447266}
         (*temporary) = nil
         (*temporary) = nil
         (*temporary) = table: 0x40386b40  {userdata: 0x014ffca0:true, userdata: 0x014e1cb0:true, userdata: 0x01539020:true (more...)}
         (*temporary) = boolean: true
         (*temporary) = table: 0x40386b40  {userdata: 0x014ffca0:true, userdata: 0x014e1cb0:true, userdata: 0x01539020:true (more...)}
         (*temporary) = table: 0x40388b58  {__gc:function: 0x40388b80, getOwner:function: 0x40388f98, __extends:table: 0x40388bb8 (more...)}
         (*temporary) = point (-1058.3033447266,1280.5748291016)  {y:1280.5748291016, x:-1058.3033447266}
         (*temporary) = string: "findObjectById"
         (*temporary) = table: 0x403872c0  {__gc:function: 0x403872e8, findAllObjectsInArea:function: 0x40387570, findAllObjects:function: 0x40387520 (m
ore...)}
         (*temporary) = C function: 0x40387398
         (*temporary) = string: "attempt to index a nil value"
(2) Lua function 'onTick' at file '~/dedicated_servers/partyserver/levels/Carnival.levelgen:1507' (best guess)
        Local variables:
         deltaTime = number: 40

**Comment by raptor** [comment]
The script did not actually cause a hard crash; only the script stopped.  I think this was a scripting error in bobdaduck's script.

**Comment by eykamp** [comment]
Ok, good.  Then it worked as designed.  By us, anyway :-)
