### ISSUE TITLE
Only emit one error for BotNavMeshZone when loading a level

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#573]
Usually these come in large batches.  The BotNavMeshZone object is harmless and an artifact from a bygone era.  A single warning per level should suffice.  Suppress the any subsequent warnings once one has been displayed during a given level load.

**Comment by bobdaduck** [comment]
Included:  Other maps that also crash, but probably which have nothing to do with navmeshzones.
[crashy maps.zip](https://github.com/bitfighter/bitfighter/files/779079/crashy.maps.zip)

**Comment by raptor** [comment]
Won't do this for 019f.  parsing levels is more complicated than previously thought, and porting to 020 would be a headache.

3 of the 4 levels do not crash any more, but one does 'Roller_Coaster.level'.  I will open a separate issue for that.

**Comment by raptor** [comment]
Fixed in 92436714d2a9b32cf68a1b0e055a79126a5bd18d
