### ISSUE TITLE
Changing level file name creates new file

### ISSUE THREAD

**Issue by fordcars** [bitfighter/bitfighter#575]
Hello!

This has been present for a while, but if you change the filename in the editor of the current level you are editing, and you save, it will save under the new name, without deleting the old one. You now have two copies of the level and you have to manually go to the levels and delete it.

Maybe we should show an alert message when changing filename to notify the player the old file will not be deleted?

**Comment by raptor** [comment]
Hi,

Is this related to issue #560 ?  Also, is this in 019e or the latest code?

**Comment by fordcars** [comment]
Oh, sorry this is in 019e, but I believe it does this too in the latest.
I don't think it's related to 560, I don't even think it's a bug. It's just not very clear changing the filename acts as a "save as" instead of a rename.

**Comment by raptor** [comment]
OK, we need to clarify that changing the name is a 'save as'...  Or, maybe disable changing the name altogether?

**Comment by eykamp** [comment]
It was always intended as "Save As".   I made the mess, I'll clean it up.

**Comment by eykamp** [comment]
I clarified the behavior; I would like to do a better fix long term, but that will probably have to wait until we get a menuing system in place.

**Comment by eykamp** [comment]
Fixed in both 019f and 020.
