### ISSUE TITLE
Replace all instances of Roman stroke font with TTF fonts

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#578]
Roman font (old-school Bitfighter font) is starting to look pretty old.  Update and replace all instances (except possibly vertex numbers in the editor) with TTF fonts.  This work is already underway, but there are still plenty of menus where stroke fonts are used.

For the moment, do not remove Roman code/code path, just make sure it isn't used without good reason.

**Comment by raptor** [comment]
I think TextItem objects should keep the Roman font, at least for now.

**Comment by eykamp** [comment]
Agreed.

**Comment by raptor** [comment]
The menus were done, there are a few things left:  diagnostics, editor teams, global chat, others?

**Comment by eykamp** [comment]
Yes -- I need to make a sweep through.  Diagnostics might be a pain, but that one can probably wait.  The Join menu will also be a pain, but we should probably do that one.

**Comment by raptor** [comment]
I think I just did 95% of this by creating a FontId of FontDefault and setting the default to FontPlay.  See commits 9a362eb544c9b9199ebfb5e6c079ec1c8600919b and a95f6bac2decc53d5be8dca510c32fa9831068e3 in the 019f branch

**Comment by raptor** [comment]
Oops, but now the editor objects are using the wrong font...

**Comment by raptor** [comment]
I don't know...  it's probably easier to invoke the OldSkoolContext on the BfObjects instead of reverting and setting all the menu fonts.  What do you think?

**Comment by eykamp** [comment]
I think you may be right. Might merge some of these font contexts at some point, but I was going to suggest trying exactly what you proposed.

**Comment by raptor** [comment]
All game objects are using OldSkoolContext now.  I think the editor dock might need it too - the font isn't super legible.  Do you have an opinion?  If you notice anything else, let me know so I can close this bug off.

**Comment by eykamp** [comment]
I skimmed through all the menus, and most look fine... the one that I feel needs a little work is the Join menu.  The dock looks ok to me on Win32; maybe it differs on Linux, in which case I have no problem at all sticking with Roman for now.

**Comment by eykamp** [comment]
Finished in 019x; still need to review 020

**Comment by eykamp** [comment]
This is now done for 020 -- Roman font only used in vertex labels (because it seems easier to read) and TextItems; we need to discuss how to get rid of them in that context as well, but it's more complicated.

If Roman pops up anywhere else in either 019x or 020, it should be considered a bug.
