### ISSUE TITLE
On game reports page, change team color when it is too light

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#581]
Find the game reoprt for Game ending on 27 Feb 2017 03:40:32 PM.  Team names are in white and very light blue.  Either add a background color, or darken the team color to be readable on a white background.

**Comment by raptor** [comment]
The way to do this is to convert the RGB to HSL (see: https://en.wikipedia.org/wiki/HSL_and_HSV) and if the 'L' is over a threshold, put a different background.

**Comment by raptor** [comment]
I added code to check the lightness and add a background.  This is what it looks like:

![image](https://cloud.githubusercontent.com/assets/6452412/23590198/fce20b9c-0198-11e7-9e2a-b28159eadd24.png)

You can fiddle with the values if wanted
