### ISSUE TITLE
Fix wiki script references

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#583]
A long, long time ago, in a galaxy far away, before the hack and subsequent server rebuild, we had a functioning Lua syntax highlighter plugged into the wiki.  It no longer seems to be functioning.

We either need to replace it, or change the formatting of pages that depended on it.  A good example is the page: 

http://bitfighter.org/wiki/index.php/Programming_levelgens

Syntax highlighting would be ideal, but even just formatting the entries as un-highlighted code would be acceptable.

**Comment by raptor** [comment]
Done!  At least, it seems to work right now...

I upgraded mediawiki to the latest security fix release for our version - we are 5 versions behind and cannot upgrade unless the server is moved to CentOS 7 or higher (due to newer php requirements)
