### ISSUE TITLE
levelgen:setGameTime() does not update client timer

### ISSUE THREAD

**Issue by fordcars** [bitfighter/bitfighter#587]
Using _levelgen:setGameTime()_ changes the server time (the game will end earlier or later depending on the time), but will not update the client timer we see on the screen.

**Comment by fordcars** [comment]
Also, in Lua docs, it would be nice to note that setting the time with _levelgen:setGameTime(0)_ as _0_ will actually set the time to infinity :)

**Comment by raptor** [comment]
Fixed in f61f6ab9169d414deea8d7f5976bec823da2cc1e
