### ISSUE TITLE
Uncaught exception during LuaException on Windows 10 64-bit (running 32-bit Bitfighter)

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#588]
This is the real bug behind @fordcars 's multitude of Lua hard crashes.  See bugs #586 #582 #576 (and maybe others).

When a Lua script error is thrown, a LuaException is raised.  However on Windows 10 64-bit running 32-bit bitfighter, the game will hard crash giving an "uncaught exception" or similar error.

I just verified this using Visual Studio 2015 on Windows 10 compiling Bitfighter 32-bit (Win32).  I used this simple levelgen script:
```
function main()
	subscribe(nil)
end

function onShipLeft(playerInfo)
end
```

**Comment by raptor** [comment]
I confirmed that this bug does *not* occur when running 64-bit Bitfighter on Windows 10 64-bit.  This means that there is some weird thing with c++ exceptions happening when running 32-bit code on Windows 64-bit.

**Comment by raptor** [comment]
Here is some technical information about how Windows does exception handling across architectures:

https://msdn.microsoft.com/en-us/library/ms633573(VS.85).aspx

It may or may not be useful.

**Comment by raptor** [comment]
Another vague clue, a few people across the web seem to say that mixing debug/release libraries and or improper library linking can cause this type of crash.

**Comment by raptor** [comment]
This only happens at that LuaException for some reason.  Other c++ exceptions are thrown and caught just fine.  If I'm reading the debugger correctly, then the LuaException is being thrown and caught OK, but somewhere during that process another exception is being thrown (Access Violation).

**Comment by raptor** [comment]
Well, it looks like that @eykamp went through all these same headaches a year and a half ago.  I backported those changes and that seems to have fixed the crashes.  See commit ded62525f82d0c044e5258f017e5ccd425324f81.

The cause of this issue is still unknown, but removing that exception fixes it.

**Comment by eykamp** [comment]
Oh, I did?  I must have blotted out the pain.  Glad the problem is fixed!
