### ISSUE TITLE
Bots don't tranverse single-point connected zones

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#591]
There is another issue now with bots since the resolution of issue #590 :  the bot in this picture can't follow the zones, I think because the boundary is now a point.  

![screenshot_8](https://cloud.githubusercontent.com/assets/6452412/24722474/104ea4bc-1a01-11e7-9101-6b3cb09d0b34.png)

**Comment by raptor** [comment]
After an insane amount of debugging what I thought was a recast error, I found out that this is due to the botzone buffering geometry for BarrierMakers only:

![screenshot_17](https://user-images.githubusercontent.com/6452412/103502747-73d8dc00-4e0f-11eb-8c01-aa2f51a1396f.png)

**Comment by raptor** [comment]
I think the *proper* solution to this is twp fold:
1. Generate zones from the entire BarrierMaker end-to-end instead of just the line segments
2. Use clipper for all the barrier geometry math instead of our home-grown stuff

And maybe the **proper** *proper* thing to do is to re-engineer the enter BarrierMaker WallSegment code entirely

**Comment by eykamp** [comment]
I think the proper proper solution would be a real pain; using clipper for barrier geometry and considering the whole wall sounds like the a more reasonable plan.

That said... the whole wall thing is kind of a dank swamp!

**Comment by raptor** [comment]
Oh man, I'm in the swamp. Why are they reduced to only line segments in the first place? I'm trying to read code comments everywhere, but I'm not sure why. Is it a network thing? PolyWalls don't do this madness.

**Comment by eykamp** [comment]
You're in the hole now... keep digging!

That is how Zap did it; you maintain a centerline, and "puff them out" in game.  That makes them much easier to manage in the editor (which was built after BF split off), and much more efficient to transmit than a polygonalized version would be.

Polywalls were something I added later; I considered doing the same puffing to make things consistent (originally they were designed to "fill in" circular walls, so I wanted them to translate seamlessly, but sanity eventually prevailed, and polywalls behave much more logically.

**Comment by raptor** [comment]
Breaking an 8-segment barrier into 8x 2-point objects can't possibly be more network efficient then sending one 9-point object, still un-puffed. What else might I be missing?

**Comment by eykamp** [comment]
Oh, that.  That was the original protocol, never changed.  You are missing the ability for ancient protocols to live on in the modern world even when there are better ways to do thing, like the chunk of cobol that is propping up the US government, running on a VMS server in some long forgotten locked closet.

**Comment by raptor** [comment]
I'm deep in the swamp and the slop is getting into my boots.

Am I correct in thinking that WallEdge, WallSegment, and WallSegmentManager are only for the editor?

**Comment by raptor** [comment]
Well, I did it. After much work I fixed botzones by handling traditional walls like polylines instead of segments:
![screenshot_19](https://user-images.githubusercontent.com/6452412/103710702-eadab580-4f72-11eb-958c-3a36c76bec52.png)
The downside, and the reason why I feel like I may have wasted my life on this, is that I found out why the segments matter, even if network-inefficient: 
* Faster grid database lookups because the segment extents are much smaller
* Rendering triangulation are always simple polygons. 
The complex polygons that can be formed vastly increase computation required to properly triangulate, and they frequently break rendering.

I want the best of both worlds.

**Comment by eykamp** [comment]
We can send polylines for network efficiency, and decompose to segments 
on the client for database purposes.  Not sure if that would help or 
hurt the triangulation situation.

Chris

**Comment by eykamp** [comment]
I believe you are correct, though by now you probably know the answer 
better than I do.

I hated writing that code.

**Comment by raptor** [comment]
One step closer. I have rewritten the code that expands a Barrier segment to a rectangle. It now creates outlines that does mitering like in Clipper (but I had to design it myself). 

While this does not directly help this issue, it does make wall corners look much less ugly. WallItems are properly sent across network as a single item, too, before they're chunked up.

See miters below (still not adapted for editor):

![Screenshot_20210111_124525](https://user-images.githubusercontent.com/6452412/104230915-6ae99b00-540b-11eb-91c3-b05baac7cfa1.png)

**Comment by raptor** [comment]
This is finally done! 

After cleaning the mitering for barriers, the solution was to merge all barriers before doing the zone buffer, then call clipper on the union to generate the buffered polygons.

Fixed ending with 38bf8305ed2681fbfe5384b3d7c64e955c927be5

I've been testing it with a number of wonky levels, and it still seems just as robust.
