### ISSUE TITLE
Fix warnings

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#593]
To the extent possible, fix the following warnings to clean up travis build:

    
    Scanning dependencies of target alure
    /home/travis/build/bitfighter/bitfighter/alure/streamplay.cpp: In function ‘void* StarterFunc(void*)’:
    /home/travis/build/bitfighter/bitfighter/alure/streamplay.cpp:89:44: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
         void *ret = (void*)(inf->func(inf->ptr));
                                                ^
    Linking CXX static library libalure.a
    Scanning dependencies of target poly2tri
    /home/travis/build/bitfighter/bitfighter/poly2tri/common/shapes.cc: In member function ‘p2t::Point* p2t::Triangle::OppositePoint(p2t::Triangle&, p2t::Point&)’:
    /home/travis/build/bitfighter/bitfighter/poly2tri/common/shapes.cc:122:10: warning: variable ‘x’ set but not used [-Wunused-but-set-variable]
       double x = cw->x;
              ^
    /home/travis/build/bitfighter/bitfighter/poly2tri/common/shapes.cc:123:10: warning: variable ‘y’ set but not used [-Wunused-but-set-variable]
       double y = cw->y;
              ^
    Linking CXX static library libpoly2tri.a
    Scanning dependencies of target clipper
    Linking CXX static library libclipper.a
    Scanning dependencies of target tomcrypt
    /home/travis/build/bitfighter/bitfighter/tomcrypt/src/pk/asn1/der/sequence/der_length_sequence.c: In function ‘der_length_sequence’:
    /home/travis/build/bitfighter/bitfighter/tomcrypt/src/pk/asn1/der/sequence/der_length_sequence.c:31:30: warning: variable ‘z’ set but not used [-Wunused-but-set-variable]
        unsigned long size, x, y, z, i;
                                  ^
    In file included from /home/travis/build/bitfighter/bitfighter/tomcrypt/src/ciphers/aes/aes_enc.c:33:0:
    /home/travis/build/bitfighter/bitfighter/tomcrypt/src/ciphers/aes/aes.c: In function ‘rijndael_enc_setup’:
    /home/travis/build/bitfighter/bitfighter/tomcrypt/src/ciphers/aes/aes.c:123:12: warning: variable ‘j’ set but not used [-Wunused-but-set-variable]
         int i, j;
                ^
    Linking C static library libtomcrypt.a
    Scanning dependencies of target tnl
    Linking CXX static library libtnl.a
    Scanning dependencies of target bitfighter_client
    /home/travis/build/bitfighter/bitfighter/zap/config.cpp: In member function ‘std::string Zap::FolderManager::getDir(Zap::FolderManager::FolderType) const’:
    /home/travis/build/bitfighter/bitfighter/zap/config.cpp:1412:1: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
    /home/travis/build/bitfighter/bitfighter/zap/gameType.cpp: In member function ‘virtual void Zap::GameType::performScopeQuery(TNL::GhostConnection*)’:
    /home/travis/build/bitfighter/bitfighter/zap/gameType.cpp:1579:9: warning: variable ‘sameQuery’ set but not used [-Wunused-but-set-variable]
        bool sameQuery = false;  // helps speed up by not repeatedly finding same objects
             ^
    /home/travis/build/bitfighter/bitfighter/zap/physfs.cpp: In member function ‘virtual std::basic_streambuf<char>::pos_type PhysFS::fbuf::seekoff(std::basic_streambuf<char>::off_type, std::ios_base::seekdir, std::ios_base::openmode)’:
    /home/travis/build/bitfighter/bitfighter/zap/physfs.cpp:34:16: warning: enumeration value ‘_S_ios_seekdir_end’ not handled in switch [-Wswitch]
              switch(dir) {
                    ^
    /home/travis/build/bitfighter/bitfighter/zap/physfs.cpp: In constructor ‘PhysFS::fbuf::fbuf(PHYSFS_File*, std::size_t)’:
    /home/travis/build/bitfighter/bitfighter/zap/physfs.cpp:89:27: warning: ‘PhysFS::fbuf::file’ will be initialized after [-Wreorder]
           PHYSFS_File * const file;
                               ^
    /home/travis/build/bitfighter/bitfighter/zap/physfs.cpp:87:20: warning:   ‘const size_t PhysFS::fbuf::bufferSize’ [-Wreorder]
           size_t const bufferSize;
                        ^
    /home/travis/build/bitfighter/bitfighter/zap/physfs.cpp:91:7: warning:   when initialized here [-Wreorder]
           fbuf(PHYSFS_File * file, std::size_t bufferSize = 2048) : file(file), bufferSize(bufferSize) {
           ^
    /home/travis/build/bitfighter/bitfighter/zap/ServerGame.cpp: In member function ‘void Zap::ServerGame::cycleLevel(TNL::S32, bool)’:
    /home/travis/build/bitfighter/bitfighter/zap/ServerGame.cpp:568:9: warning: variable ‘triangulate’ set but not used [-Wunused-but-set-variable]
        bool triangulate;
             ^
    /home/travis/build/bitfighter/bitfighter/zap/ServerGame.cpp: In member function ‘void Zap::ServerGame::buildBotMeshZones(bool)’:
    /home/travis/build/bitfighter/bitfighter/zap/ServerGame.cpp:690:84: warning: the address of ‘bool Zap::triangulate(const TNL::Vector<TNL::Vector<Zap::Point> >&, TNL::Vector<TNL::Vector<Zap::Point> >&)’ will always evaluate as ‘true’ [-Waddress]
           mLevel->getSqliteLevelId(), writeZonesToDb, mSettings->usingDatabaseZoneCache);
                                                                                        ^
    /home/travis/build/bitfighter/bitfighter/recast/RecastMesh.cpp: In function ‘bool buildMeshAdjacency(short unsigned int*, int, short unsigned int*, int, int)’:
    /home/travis/build/bitfighter/bitfighter/recast/RecastMesh.cpp:134:20: warning: unused variable ‘p0’ [-Wunused-variable]
        unsigned short* p0 = &adjaceny[e.poly[0]*vertsPerPoly];      // l-poly
                        ^
    /home/travis/build/bitfighter/bitfighter/recast/RecastMesh.cpp:135:20: warning: unused variable ‘p1’ [-Wunused-variable]
        unsigned short* p1 = &adjaceny[e.poly[1]*vertsPerPoly];      // r-poly
                        ^
    /home/travis/build/bitfighter/bitfighter/recast/RecastMesh.cpp: At global scope:
    /home/travis/build/bitfighter/bitfighter/recast/RecastMesh.cpp:41:13: warning: ‘bool buildMeshAdjacency(short unsigned int*, int, short unsigned int*, int, int)’ defined but not used [-Wunused-function]
     static bool buildMeshAdjacency(unsigned short* polys, const int npolys,
                 ^
    /home/travis/build/bitfighter/bitfighter/recast/RecastMesh.cpp:248:13: warning: ‘bool intersect(const int*, const int*, const int*, const int*)’ defined but not used [-Wunused-function]
     static bool intersect(const int* a, const int* b, const int* c, const int* d)
                 ^
    /home/travis/build/bitfighter/bitfighter/zap/EditorWorkUnit.cpp:161:13: warning: ‘void Zap::Editor::getGeometries(const TNL::Vector<boost::shared_ptr<Zap::BfObject> >&, TNL::Vector<TNL::Vector<Zap::Point> >&)’ defined but not used [-Wunused-function]
     static void getGeometries(const Vector<boost::shared_ptr<BfObject> > &objects, Vector<Vector<Point> > &geoms)
                 ^
    /home/travis/build/bitfighter/bitfighter/zap/UIEditor.cpp: In member function ‘void Zap::EditorUserInterface::renderTurretAndSpyBugRanges(Zap::GridDatabase*) const’:
    /home/travis/build/bitfighter/bitfighter/zap/UIEditor.cpp:1640:11: warning: variable ‘prevTeam’ set but not used [-Wunused-but-set-variable]
           S32 prevTeam = -10;
               ^
    /home/travis/build/bitfighter/bitfighter/zap/UIItemListSelectMenu.cpp: In member function ‘virtual void Zap::PlaylistMenuUserInterface::onActivate()’:
    /home/travis/build/bitfighter/bitfighter/zap/UIItemListSelectMenu.cpp:308:16: warning: unused variable ‘game’ [-Wunused-variable]
        ClientGame *game = getGame();
                    ^
    /home/travis/build/bitfighter/bitfighter/zap/UIItemListSelectMenu.cpp: At global scope:
    /home/travis/build/bitfighter/bitfighter/zap/UIItemListSelectMenu.cpp:362:13: warning: ‘void Zap::processPlaylistInGameSelectionCallback(Zap::ClientGame*, TNL::U32)’ defined but not used [-Wunused-function]
     static void processPlaylistInGameSelectionCallback(ClientGame *game, U32 index)             
                 ^
    /home/travis/build/bitfighter/bitfighter/zap/UIQuickMenu.cpp: In member function ‘virtual void Zap::QuickMenuUI::render() const’:
    /home/travis/build/bitfighter/bitfighter/zap/UIQuickMenu.cpp:199:8: warning: unused variable ‘x2’ [-Wunused-variable]
        S32 x2 = instrXPos + helpWidth / 2 + margin;
            ^
    /home/travis/build/bitfighter/bitfighter/zap/UITeamDefMenu.cpp: In member function ‘virtual void Zap::TeamDefUserInterface::render() const’:
    /home/travis/build/bitfighter/bitfighter/zap/UITeamDefMenu.cpp:245:11: warning: unused variable ‘i’ [-Wunused-variable]
           S32 i = j + 2;    // Take account of the two fixed teams (neutral & hostile)
               ^
    /home/travis/build/bitfighter/bitfighter/zap/glad.c:145:12: warning: ‘num_exts_i’ defined but not used [-Wunused-variable]
     static int num_exts_i = 0;
                ^
    /home/travis/build/bitfighter/bitfighter/zap/glad.c:182:12: warning: ‘has_ext’ defined but not used [-Wunused-function]
     static int has_ext(const char *ext) {
                ^

**Comment by raptor** [comment]
I see these warnings all the time - I usually just leave them until we get close to release.  They're not normally turned on unless you do a debug build (which I enabled in the Travis build).

If you want to see a lot more warnings, compile with clang and extra verbosity.

**Comment by eykamp** [comment]
Most of them are either trivial to fix, or good to fix.  I'm going to 
spend about 20 mins on this story, and will live with anything I can't 
fix in that time frame.

**Comment by eykamp** [comment]
80% fixed, 20% tolerated
