### ISSUE TITLE
Sort out Releases page on the website

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#598]
What is the purpose of the Releases page in this era?  It has tons of broken links; we don't really need anything more than the most recent version and maybe one back; the File Size column should be deleted (or populated), and there are lots of releases that are missing.

Maybe that page could be converted to a wiki entry where release dates could be provided for historical interest?

**Comment by eykamp** [comment]
And the release date for 018/018a seems a bit muddled.

**Comment by raptor** [comment]
I was thinking of maybe just making a file listing via apache to fulfill the file need.  I don't know if we need a long-term changelog.

**Comment by eykamp** [comment]
I made a small start by removing duplicate releases for different platforms, and removing the largely unpopulated filesize column, and removing the broken links to older installers.  

I like having the old changelogs available, as it is a good reminder of how far we've come.  That could potentially move to a wiki page, though, in which case we could abandon the releases page altogether.

**Comment by raptor** [comment]
Current page seems OK. It's a changelog history page now with no broken links.
