### ISSUE TITLE
bitfighter fails to build against new luajit 2.1.0 (beta3)

### ISSUE THREAD

**Issue by david-geiger** [bitfighter/bitfighter#602]
Hi,

On Mageia Cauldron we tried to compile bitfighter against luajit 2.1.0 beta3 but it fails to build due to some compat symbols removed upstream, for reference:

https://github.com/LuaJIT/LuaJIT/issues/325

So this proposed patch fixes build:

http://svnweb.mageia.org/packages/cauldron/bitfighter/current/SOURCES/bitfighter-019f-mga-luajit-2.1.patch?view=markup&pathrev=1201685

Regards,
David

**Comment by eykamp** [comment]
That looks simple enough; thanks!!

**Comment by raptor** [comment]
Patch committed.  Thanks!
