### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by constatinus** [bitfighter/bitfighter#605]
Hi all.
I was just trying to compile this version from git but suddenly after i ran cd build && cmake i got this log:

Make Error at master/CMakeLists.txt:93 (add_dependencies):
  The dependency target "sqlite" of target "master_lib" does not exist.

CMake Error at master/CMakeLists.txt:93 (add_dependencies):
  The dependency target "tomcrypt" of target "master_lib" does not exist.

CMake Error at zap/bitfighterd.cmake:11 (add_dependencies):
  The dependency target "/usr/lib/x86_64-linux-gnu/libluajit-5.1.so" of
  target "bitfighterd" does not exist.
Call Stack (most recent call first):
  zap/CMakeLists.txt:276 (include)

CMake Error at zap/bitfighterd.cmake:11 (add_dependencies):
  The dependency target "sqlite" of target "bitfighterd" does not exist.
Call Stack (most recent call first):
  zap/CMakeLists.txt:276 (include)

CMake Error at zap/bitfighterd.cmake:11 (add_dependencies):
  The dependency target "tomcrypt" of target "bitfighterd" does not exist.
Call Stack (most recent call first):
  zap/CMakeLists.txt:276 (include)

CMake Error at zap/bitfighter_client.cmake:14 (add_dependencies):
  The dependency target "/usr/lib/x86_64-linux-gnu/libluajit-5.1.so" of
  target "bitfighter_client" does not exist.
Call Stack (most recent call first):
  zap/CMakeLists.txt:279 (include)

CMake Error at zap/bitfighter_client.cmake:14 (add_dependencies):
  The dependency target "sqlite" of target "bitfighter_client" does not
  exist.
Call Stack (most recent call first):
  zap/CMakeLists.txt:279 (include)

CMake Error at zap/bitfighter_client.cmake:14 (add_dependencies):
  The dependency target "tomcrypt" of target "bitfighter_client" does not
  exist.
Call Stack (most recent call first):
  zap/CMakeLists.txt:279 (include)

-- Generating done 

of course, i have all the dependencies specified in the readme file and a clean build dir. Everything execpt poly2tri and tomcrypt which i have but isn't dected. Help ?
Full log here: https://pastebin.com/LxwcDUwk

**Comment by raptor** [comment]
Hi,

Instructions for building are here:

http://bitfighter.org/wiki/index.php/Building_Bitfighter

How did you get the source code and what OS/platform are you running?

**Comment by constatinus** [comment]
Via git, of course, just now. I also tried the release version 019f, still the same issue.

**Comment by constatinus** [comment]
If i do continue do to `make` , i get: https://pastebin.com/KuVCyCif

**Comment by raptor** [comment]
CMake must complete successfully before `make` will work.  

The release version is the supported version for building.  If you follow the instructions and checked out bitfighter-019f, you'll have to delete the CMakeCache from any previous attempts on a different branch.

What OS/platform are you on?

**Comment by constatinus** [comment]
Linux. Even if i cleared CMakeCache and the build folder itself, the problem persists.

**Comment by raptor** [comment]
I need more information about how you're building:
 - What platform are you on?  (E.g. Ubuntu 12.04 x86_64)
 - What version of CMake are you using?
 - What is the full cmake log on the bitfighter-019f checkout with a clean 'build' directory? This will be different than what you originally posted

Then I can determine if it is a bug on our end or not.

Thanks

**Comment by constatinus** [comment]
Debian 9.4 ,x86_64
CMake 3.10.1, compiled ( i now tried with 3.1.0, the same problem )
I don't understand what cmake log? I gave an pastebin of the full log, i don't know if theres anything other than that?

**Comment by raptor** [comment]
Thank you.  
Yes, a pastebin of the log (or the output) of CMake is what I'm looking for, when it is done with a clean build directory on the bitfighter-019f tag.  The previous log you gave was on the master branch which is broken right now.

**Comment by constatinus** [comment]
I just solved the cmake WARNINGS by using cmake-2.8.8. The lua errors still persist.

**Comment by raptor** [comment]
Hi,

The warnings are known to happen with later CMake and do not matter with compiling the game.  The errors are the issue.  

I would still like to see that CMake output with a clean build directory on bitfighter-019f.

If you are using system LuaJIT, you could try and force the compile to use the in-tree version by commenting out everything but what's in the `else()` section of the CMakeLists.txt here:

https://github.com/bitfighter/bitfighter/blob/master/CMakeLists.txt#L240-L250

**Comment by constatinus** [comment]
Thanks much! Now it works but with this issue [https://github.com/bitfighter/bitfighter/issues/603](url) with i managed to temp. "fix" with running valgrind.

**Comment by raptor** [comment]
Committed change in CMakeLists to default to in-tree LuaJIT
