### ISSUE TITLE
s-bots should avoid gofasts

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#606]
If a go-fast is pointing opposite where a bot wants to go, the bot should not fly into it.  A bot should be able to navigate the following from A to B by flying around the go-fast, especially if the power is such that the bot can't "swim upstream".  If the power is low, perhaps it could account for the cost of hitting it when creating its flight-plan.  Not sure how to handle angled go-fasts.

A     <<     B

**Comment by Xelor41023** [comment]
On a Slightly Related Note  Should This Be Applied To Teleporters As Well?

**Comment by eykamp** [comment]
I believe bots are smart enough to use teleporters where they can; I'm not sure if they are smart enough to avoid them when they go somewhere the bot doesn't want to go.  If not, I agree.

**Comment by Xelor41023** [comment]
Might be doable by having s_bot "calculate" if the speed zone will have him in a zone farther down its trajectory path to the target.

**Comment by raptor** [comment]
Current idea to solve is:
- mesh the bot zones under SpeedZone objects separately
- only allow one-way zone connection into the SpeedZone
- create a connection out of the SpeedZone to some outside side a distance away based on the speed of SpeedZone

That last one will not be exact, but maybe good enough. Thoughts?

**Comment by eykamp** [comment]
I think this would be an improvement; the flaw in the 3rd step is if the speedzone bounces you off something, it may not be clear where the exit should be considered.  That said, it would be a big improvement, which, even if imperfect, is better than no improvement.

**Comment by raptor** [comment]
My current plan is to use existing line-of-sight and ray-bounce code we have lying around to determine a likely stopping point, then make a connection to the zone that covers that point.

**Comment by eykamp** [comment]
Your idea is remarkably similar to what I was thinking, except I was imagining a series of stimulated passes through the GF starting from various points.  Rather than the stopping point, you probably want the "return to normal speed" point.  I suppose if snapping in enabled, the problem becomes simpler yet.

The case of a GF blasting straight into a core is probably too corney to worry about.

**Comment by raptor** [comment]
I did a few tests with GoFasts (is the official name supposed to be 'GoFast' or 'SpeedZone'?).

It turns out that the distance a ship travels is proportional to the square of the speed on the SpeedZone, but it also depends on the snapping and starting velocity of the ship. Even if snapped, the end range of the ship could be anywhere within 200 points or so, but larger if the speed is faster.

I'm not sure how deterministic it is, even for Robots. I was thinking that as a fallback I could always just program it to the point almost directly in front of the zone.

**Comment by raptor** [comment]
I've been working on this all week and I have most cases working OK. I can more-or-less predict a single barrier bounce, but two or more bounces requires I know how the natural ship deceleration works. I cannot seem to find or deduce this in the code. Do you have an idea?

**Comment by eykamp** [comment]
Well... not sure.  I tried to figure this out once, and didn't.

What might be happening is the ship is being slowed by the application 
of the "move".

This code, in ship.cpp, gets my attention:

    F32 maxVel = (mLoadout.isModulePrimaryActive(ModuleBoost) ? 
BoostMaxVelocity : MaxVelocity) *
                 (hasModule(ModuleArmor) ? ARMOR_SPEED_FACT : 
NORMAL_SPEED_FACT);

    F32 time = mCurrentMove.time * 0.001f;

    static Point requestVel, accel;     // Reusable containers

    // This is what the client requested -- basically requestVel.len() 
will range from 0 to 1; any higher will be clipped
    requestVel.set(mCurrentMove.x, mCurrentMove.y);
    requestVel *= maxVel;

    static const S32 MAX_CONTROLLABLE_SPEED = 1000;

    // If you are going too fast (i.e. > MAX_CONTROLLABLE_SPEED), you 
cannot move, and will automatically
    // "hit the brakes" by requesting a speed of 0
    if(getVel(stateIndex).lenSquared() > sq(MAX_CONTROLLABLE_SPEED))
       requestVel.set(0,0);

We are, in effect, "requesting" a move with a maxVel of 0 if we're going 
too fast.  That drives an acceleration computation, which then feeds 
into a velocity computation.

But how this translates into a distance traveled... ???  change in v = 2 
* a * distance; dv = initial velocity - 450.  Oh, and look, in ship.h 
there is an acceleration (2500) maybe that plugs in?

distance flung = (inital vel - 450) / 2500   ?  Could it be that easy?

Chris

**Comment by raptor** [comment]
That's the exact code I've just been staring at. You may be onto something about applying a different equation at different speeds. That equation doesn't quite work for distance - maybe it's the delta-v (per ms).

FYI, I had already calculated the distance experimentally as roughly:
```
F32 distanceEstimate = .00045 * speed * speed;
```
But it fails after bouncing off 2 barriers.

Thanks for looking at it and triggering some more ideas.

**Comment by eykamp** [comment]
Bouncing probably depletes some speed, so there might be an additional factor based on that.

On Sat, Feb 20, 2021, at 09:22, raptor wrote:
> 

> That's the exact code I've just been staring at. You may be onto something about applying a different equation at different speeds. That equation doesn't quite work for distance - maybe it's the delta-v (per ms).

> FYI, I had already calculated the distance experimentally as roughly:

> `F32 distanceEstimate = .00045 * speed * speed;
`

**Comment by raptor** [comment]
I think I got it!

![screenshot_33](https://user-images.githubusercontent.com/6452412/108887050-f76ca900-75c6-11eb-9fd4-deefdd5e13ce.png)

The green line from the SZ is the prediction, and the ship is where it ended up after entering the SZ and bouncing through all 4 walls.

**Comment by eykamp** [comment]
Brilliant!

**Comment by raptor** [comment]
OK, it is now much smarter and can do better on certain corner cases (like bouncing off of wall corners).

Bonus videos!:

https://user-images.githubusercontent.com/6452412/110258877-f857f000-7f61-11eb-85e8-a1e2362b7b61.mp4

https://user-images.githubusercontent.com/6452412/110258920-2b01e880-7f62-11eb-9478-7255f46c67ac.mp4

**Comment by raptor** [comment]
Resolved in 909cdd1403272c8b13e0b2071004303e503dd609
