### ISSUE TITLE
Fix compilation of TNLPing on Raspberry Pi

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#612]
Compiling of TNLPing failed on Raspberry Pi, following the directions on in readme.md.

There were two main issues: the makefile for libtomcrypt required .o files that were not able to be generated (deleting these from the generated makefile addressed that issue), and the makefiles were looking for things in the libtomcrypt folder rather than the tomcrypt folder where they actually were.

It is likely these issues impact more than TNLPing, and more than Raspberry Pi, but that's where I found them.

**Comment by raptor** [comment]
Hi!

Did this happen if you used the CMake system?  There should not be any Makefiles left around, they should be generated by CMake.

**Comment by raptor** [comment]
By which I mean you can:
- cd build
- cmake ..
- make tnlping

**Comment by eykamp** [comment]
Yes -- I ran cmake first on a clean clone, then used make with the resulting makefiles. By modifying the makefile in tomlib (removing 3, if I recall, .o files from the long list), and adding the symlink, it worked properly.

One thing I did not do was a full build -- I started with tnlping (I don't recall if I had to run make separately in tomlib). I'm curious about server performance on the Raspberry Pi, so I may do the full build at some point in the future. It is conceivable that building everything will be more successful.

**Comment by raptor** [comment]
OK. It may be the CMakeLists just needs to be altered.

Once upon a time I compiled bitfighter 018a on a RPi 1.  I remember it working with a handful of bots (less than 10, I think) but not much more.

**Comment by fordcars** [comment]
If I remember right, Bitfighter on RPi2 could handle quite a bit of bots (around 35 or something!)

**Comment by raptor** [comment]
I just compiled lastest code on a raspberry pi 3B+. Both `bitfighterd` and `tnlping` work fine.
