### ISSUE TITLE
Client-side prediction wrong with Bouncer

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#614]
@bobdaduck has a Nexus map where after some time, the server adds Barriers via script. The client cannot receive Barrier objects due to the game's architecture, so he sends LineItems to draw out the new Barriers on the client.  

All weapons when shot at the new Barriers stop or bounce back with some minor client-side prediction artifacts.  Except Bouncer, it goes right though and isn't properly updated on the client. I suspect some bit is missing in the TNL stream to force updates for Bouncer.

**Comment by bobdaduck** [comment]
[level.zip](https://github.com/bitfighter/bitfighter/files/4561760/level.zip)

**Comment by raptor** [comment]
Fixed in 9d9fa49a78277c9f107045db1b04309d81eeb8c9
