### ISSUE TITLE
Using the F4 functions causes the game to switch views

### ISSUE THREAD

**Issue by TheSkybax** [bitfighter/bitfighter#617]
019g
Windows 10 x64

It switches between fullscreen and fullscreen stretched, making things look funky. Note that it does not reflect the change in the menu.

How I duplicate the bug 100% accuracy

Open the level editor to any level
Use any function (I.E. ctrl+;)
Confirm the function
The view switches

![screenshot_50](https://user-images.githubusercontent.com/7220369/82508540-3c086880-9aba-11ea-8ea3-52e0bf3ee5bd.png)
![screenshot_51](https://user-images.githubusercontent.com/7220369/82508541-3ca0ff00-9aba-11ea-8b39-d3bbc252decb.png)
![screenshot_52](https://user-images.githubusercontent.com/7220369/82508542-3d399580-9aba-11ea-9760-0653ca0fb02a.png)
![screenshot_53](https://user-images.githubusercontent.com/7220369/82508543-3d399580-9aba-11ea-8ce2-f6b2dd2c8ac9.png)
![screenshot_54](https://user-images.githubusercontent.com/7220369/82508545-3dd22c00-9aba-11ea-8160-60f66e9fd718.png)

**Comment by raptor** [comment]
Duplicated on Linux x86_64, too. 

I suspect the plugin menu is not returning to the proper editor display mode. Might be a consequence of rewriting the game display mode states and not handling that case.

**Comment by raptor** [comment]
This was a gnarly bug. Fixed in 124c2a1ffb761d15280795333880de5e29798877
