### ISSUE TITLE
Fix luadocs

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#620]
The process for updating the luadocs is to run:

```perl luadoc.pl```

with doxygen 1.8+ at the root of the bitfighter source tree.

This produces many warnings/errors because of typos and bad links internal to our code documentations. Fix these, starting with the most current output (attached) from 019g:

[luadoc_warnings.txt](https://github.com/bitfighter/bitfighter/files/4682678/luadoc_warnings.txt)

**Comment by monkeynaleo** [comment]
#633 The only errors that I have left are:
```
bitfighter/doc/temp-doxygen/main_page_content.h:328: warning: unable to resolve link to `Robot::subscribe' for \link command
bitfighter/doc/temp-doxygen/main_page_content.h:328: warning: unable to resolve link to `LuaLevelGenerator::subscribe' for \link command
```
What pages are meant to be referenced?  I cannot find any pages on the subscribe methods which these pages should be referring to.

**Comment by raptor** [comment]
Closing as this work was included and @eykamp has started improving them further. Thanks!
