### ISSUE TITLE
New module idea ("Tick")

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#627]
This new module would allow you to attach yourself to an enemy player.  You will become invisible, and the player you are attached to will not know you are attached.  You will be able to fire (perhaps your bullets would be invisible to the player you are attached to), damaging other enemy players, and would be immune to damage while attached to the host.  When the host is killed, you would appear in their place, and continue as normal from there with the same health you had when you attached.

Ticks would be visible to players with sensor, could (perhaps) be visible to the tick's teammates, and could not attach to players with sensor.  In Nexus games, ticks and hosts would split the points of any scored flags.

Not sure this is a good idea, but I encountered a lot of ticks this past weekend, and that got me thinking.

**Comment by TheSkybax** [comment]
This sounds like an idea that would totally alter the game for many players lol
Also who would want to sit on someone and not move the whole game?

**Comment by bobdaduck** [comment]
Alt: Make a tickbug object that functions sort of like this that you can plant by double-tapping when cloaked, or as a secondary feature to the tick module

**Comment by eykamp** [comment]
Not the whole game -- just until the host was killed.
