### ISSUE TITLE
Create /setGlobalScript chat command

### ISSUE THREAD

**Issue by bobdaduck** [bitfighter/bitfighter#630]
With the addition of a global script host option, I predict global scripts are going to see much more play than before.  It would be fantastic for many of these scripts, such as the overtime script I just created, to be settable on-the-fly, for example in response to a user's request.  This overtime script would also make a great addition as a script to include with bitfighter by default.

[overtime.zip](https://github.com/bitfighter/bitfighter/files/4789705/overtime.zip)

**Comment by raptor** [comment]
Added in cb3d4b8d445416f2d05566e142ce660662e417f6
