### ISSUE TITLE
new /comment ingame command

### ISSUE THREAD

**Issue by bobdaduck** [bitfighter/bitfighter#632]
/comment <string>

submits comment to Pleiades level if applicable

**Comment by bobdaduck** [comment]
![image](https://user-images.githubusercontent.com/3999623/85802328-f87ccc00-b701-11ea-97b5-b7716043a066.png)

**Comment by raptor** [comment]
Do you mean when a level is first uploaded? Or that this is broke?

**Comment by bobdaduck** [comment]
Sorry I don't know how to tag this as a "new feature"

It would be incredibly convenient to be able to submit comments on levels from in-game that would then show up in Pleiades.

**Comment by TheSkybax** [comment]
One hundred times yes

**Comment by raptor** [comment]
Done in 48f0949f2caa903241b702bf23af335577e628eb
