### ISSUE TITLE
/settime multiplies the time entered by 1000, but only when a vote is required

### ISSUE THREAD

**Issue by Jomskylark** [bitfighter/bitfighter#635]
**BF version:** 021, but occurred in 019g as well
**OS/arch:** Mac OS X but seems to be a cross-platform issue

**Describe the bug**
Attempting to change the game time via vote results in a weird bug where the time entered is actually multiplied by 1,000. This only occurs when a vote is required, not when you're alone in a server changing the time or when you have appropriate privileges to not need a vote. 

**To Reproduce**
1. Go to a server where you have permission to change the time, but changing the time requires approval or abstains from other players via vote.
2. Type /settime x, where x is the number of minutes you want to change the game time to. For example, /settime 5 for 5 minutes
3. It will appear normal to other players: They will be presented with a vote to change the game time to 5 minutes.
4. Have the other players approve the vote (or abstain) and watch as whatever time entered is multiplied by 1,000. For /settime 5, this is 5,000 minutes.

The workaround I've used has been to divide whatever game time I want to have happen by 1,000, ie. for a 5 minute game I would type /settime 0.005. However, this vote appears to other players as 0 minutes 0 seconds, so there's a good chance the vote gets axed.

**Other**
I can take a video with Arctic if you'd like, but this is pretty straightforward to reproduce.

Thanks!

**Comment by eykamp** [comment]
This is almost certainly forgotten (or extra) ms to s conversion in there somewhere.  Probably a very easy fix.

**Comment by raptor** [comment]
Fixed in adb298eb2afde4c75a8d03dfab47497d1bf0954e
