### ISSUE TITLE
Linux download link broken on website.

### ISSUE THREAD

**Issue by elementc** [bitfighter/bitfighter#637]
**BF version:** `21`
**OS/arch:** `Linux`

**Describe the bug:**
When attempting to download on bitfighter.org, the linux build is currently 404'ing.

**To Reproduce**

1. Navigate to http://bitfighter.org/downloads/
2. Click Linux > Standalone.
3. Observe http://bitfighter.org/files/bitfighter-021-linux-standalone.tar.gz is a 404

**Comment by raptor** [comment]
Thanks!

Turns out I lost my notes/scripts on how to make a standalone build from RPMs *and* since 021 uses c++11 and other newer features glibc 2.7 compatibilty will have to be dropped, too.

I'm considering making this an AppImage, but it'd be x86_64 only. Thoughts?

**Comment by elementc** [comment]
I'm literally working on a config file to make this a snap package right now, mostly because I want to learn snap and flatpak. AppImage would be grand instead if it's pretty straightforward, you're concerned that it won't work on aarch64? What's the barrier there?

**Comment by elementc** [comment]
Oh, you're worried about dropping 32bit x86 support. The fact that I just *assumed* you were talking about ARM probably says all it needs to- 32bit x86 is on the way out for the most part, I don't think it will be cried over.

**Comment by raptor** [comment]
I've made several AppImage packages for other softwrae projects, but only for x86_64. The only barrier is my current knowledge. 

Yeah, do you think an AppImage for x86_64 would suffice? I don't think I've seen an x86 (32 bit only) platform in quite a while...

**Comment by elementc** [comment]
I say let's plow forward with x64 for now! If 32bit is sorely missed, having a working x86_64 config is probably a better starting point than nothing :)

Are the other projects you've done this for open source? Happy to go take a whack at it right now while my editor's open, if there's some other project I can use as a guide.

**Comment by raptor** [comment]
Update: I just found my old scripts to do the standalone build and sure enough, they no longer work because of ABI changes. I'm gonna try and fix it, but I may to do an AppImage. 

For AppImages, I use the Open Build Service with AppImage integration, see here:

   https://docs.appimage.org/packaging-guide/hosted-services/opensuse-build-service.html#ref-obs

There is quite a bit of setup involved, though.

**Comment by elementc** [comment]
Didn't get to appimage tonight, but polished up snap if you guys want it: https://github.com/bitfighter/bitfighter/pull/638
Still want to do flatpak and appimage as exercises at some point.

**Comment by raptor** [comment]
Temporary AppImage:

   http://bitfighter.org/~raptor/bitfighter-021-Build0.glibc2.14-x86_64.AppImage

**Comment by raptor** [comment]
Added AppImage to replace old standalone version here:

   https://bitfighter.org/downloads/
