### ISSUE TITLE
Make zone:getPos() return center of zone

### ISSUE THREAD

**Issue by bobdaduck** [bitfighter/bitfighter#643]
since zones are geom their setPos function is null but it would actually be useful for translating object geoms to know the "center" of the zone

**Comment by raptor** [comment]
There is Geom::centroid() method available. 

It has some differences with how the centroid is calculate in game: it calculates the geometric mean instead of the center of mass and it is done in Lua instead of the c++ code.

Would this be sufficient?

**Comment by bobdaduck** [comment]
Probably. I'm specifically trying to rotate full zone geoms around their centers (like just pressing R in the editor) but either way just having it return something decently close to the center of even just basic shapes would be good enough
