### ISSUE TITLE
Game display gone whack

### ISSUE THREAD

**Issue by ianeyk** [bitfighter/bitfighter#644]
**BF version:** `021`
**OS** `Windows 10 (on a Dell laptop)`

**Describe the bug**
`The display looks like the screenshot below, in all parts of the game (in game, editor, and menus), and for windowed, fullscreen, and fullscreen stretched modes. The game is playable and all controls work. Using the in-game screenshot (ctrl+q), produces an image that looks normal, as in the second screenshot.`

**To Reproduce**
`Open Bitfighter.`

**Other**
Screenshot from my computer
![image](https://user-images.githubusercontent.com/3397038/102927840-ba205980-4465-11eb-84c6-5baf1ac97b96.png)

Screenshot from in-game, by pressing ctrl+q
![screenshot_12](https://user-images.githubusercontent.com/3397038/102928432-ac1f0880-4466-11eb-989e-f56c7411a0cc.png)

My device manager window, showing my graphics card
![image](https://user-images.githubusercontent.com/3397038/102929802-454f1e80-4469-11eb-9d96-7008ae054e62.png)

**Comment by raptor** [comment]
Wow, that's trippy!

Can you determine which video card the game is running on?  NVIDIA or Intel?

If you have both, is this an NVIDIA optimus setup where it switches between the two?

Try forcing the game to run on one or the other somehow.

**Comment by ianeyk** [comment]
By default, Bitfighter uses the integrated graphics card (Intel UHD), but using the NVIDIA app that comes with the machine, I can force Bitfighter to use the NVIDIA graphics card, which solves the problem.

For me the problem is resolved, but it probably shouldn't behave that way in the first place.

There didn't seem to be any settings I could play with for the Intel graphics card, but I am happy to test anything that would be helpful.

**Comment by TheSkybax** [comment]
I feel like that may have been a setting on your motherboard and not so much a Bitfighter setting.. games don't usually get to dictate what graphics card they run off of, your system does that

**Comment by raptor** [comment]
This is almost certainly a driver issue. 

I have a laptop with NVidia + Intel graphics that can switch between them, and I've gone through times where one chip or the other will work with things.

Will close for now.
