### ISSUE TITLE
Make the Lua console available during games

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#650]
We should allow users to display the Lua console during a game, perhaps only when testing a level (to avoid accidental activation during a firefight).  When working on recent scripts, I found debugging to be very tedious and frustrating, and the console would make it easier for folks to see messages that were displayed without resorting to the hackery I resorted to.  

We may want to do other things as well, but this seems like an easy step to start with.

**Comment by raptor** [comment]
Do you mean something other than the in-game oglconsole `CTRL+/`? All the Lua outputs do redirect here.

**Comment by eykamp** [comment]
Yes, exactly like that.
