### ISSUE TITLE
Wall-related object hierarchy is confusing

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#652]
I think it's confusing because of the naming conflicts. See attached picture.

The level file uses `BarrierMaker` yet in the code it is `WallItem` that gets later combined with `PolyWall` to all become a `Barrier`.

And the Editor doesn't seem to use `Barrier` anywhere, rather the original `WallItem` and `PolyWall` objects.

How can we fix this? Do we need to fix this?

Given three contexts, client/server/editor, a database search on the server and client will only return `Barrier`. But the editor will return `WallItem` and `PolyWall` (and `WallSegment`, and `WallEdge` which are important to editor functions). 

Is there any way to do this better?

![bf_wall_object_hierarchy](https://user-images.githubusercontent.com/6452412/104233763-af773580-540f-11eb-89b6-71918fb3d1cc.png)

**Comment by eykamp** [comment]
If it is a naming problem, we can change the classes at will, release a new version of the level code to change them there, and/or release a new major version and change the protocol names.

in this case, the "how to do it" is much easier than the "what to do.". But now that you're in the middle of it, do you think the basic object hierarchy, names aside, makes sense?

Maybe settling on "wall" makes sense... Wall, PolyWall, NetWall, WallEdge, WallManager, etc.

**Comment by raptor** [comment]
Yes, I fully agree - the 'how' is cake.

I think the editor hierarchy is good for what it needs to do and I don't see changing it much. I'd say there are two main things that I'd consider changing:
1. The names of `BarrierMaker` and `WallItem`, then `Barrier` later for all walls as the game object.
2. Consolidating the (currently named) `Barrier` and `WallSegment` objects

For point 1, The `BarrierMaker` name in level files has a lot of historical pressure and I'm most hesitant to change it. Perhaps we should change 'WallItem' to 'BarrierMaker' and then change 'Barrier' to 'WallItem'. (it might depend on what you think the difference is between a 'barrier' and a 'wall'. Is one a superset of another?)

For point 2, I haven't delved into the editor code too much yet and I don't know if these two objects can be combined, but they server similar purposes.

**Comment by raptor** [comment]
I cannot find the reason that WallSegment (used in the editor) is different than Barrier (used in client/server), other than Barrier is constructed after network code (via WallRec). Both are psuedo objects used to convert the line geometry into polygons. Do you know why the editor diverged this object in this manner?

**Comment by eykamp** [comment]
I don't. a likely explanation is that they're written by different people at different times for different purposes, and when I was developing editor I may not have fully understood how walls worked in other parts of the system.

The editor was developed pretty early on
In my BitFighter trajectory. 

If it looks like combining them is the right move, then I am all for it.

**Comment by raptor** [comment]
Closing this issue - it is now well understood! :)
