### ISSUE TITLE
Bot zone navigation problems with Cores

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#653]
The stock 'core' map breaks bots badly (see picture below). This is because bot zones are built underneath the core but are blocked by them. The stock map uses this blocking technique in several places.

The solution cannot be to exclude the area below the cores because then the bots do not find a path from one side of the map to the other, or through the teleporters.

Some possible solutions:
1. dynamic bot zone reconfiguration (issue #222 )
2. weighted zones that signal the A* algo a higher cost
3. something else

![bot_stuck_core](https://user-images.githubusercontent.com/6452412/106536158-1343ca00-64b5-11eb-8879-61d16dc848f7.png)

I want to finally fix this to add to other changes that would make bots be significantly better for next release.

Related issues: #222 , #606

**Comment by raptor** [comment]
I think a first step would be to guarantee a zone shape of the size we want below the object.

**Comment by raptor** [comment]
Getting closer!

![screenshot_27](https://user-images.githubusercontent.com/6452412/106995258-bc035b00-673b-11eb-8dbc-67fcc91e1dc4.png)

**Comment by eykamp** [comment]
That looks fantastic!  One idea might be to assign a very high cost to traversing the core zone, and then reducing it once the core is destroyed. that might lessen the amount of recalculation required, as the connectivity and adjacency would not change, only the cost used to calculate the bots path

**Comment by raptor** [comment]
Yes, that's an excellent idea. Best one yet, I think, about how to handle it.

On another note - I was looking into updating Recast, but it looks like our version is *heavily* modified. When comparing what we have to an upstream version, I could not find a single one that matched from that time period. Some of the code looks refactored, some ripped out and put into Bitfighter, and some disabled or bypassed completely.

Do you remember what happened during that time period that made us do such radical changes to the upstream library? The commit logs aren't that enlightening...

**Comment by eykamp** [comment]
I do not, and am surprised by your report.  There was that very intense week where you and I were really focused on the zone generation and we wrote a lot of great code and maybe that's when it happened?  That said, it's hard for me to imagine us rewriting parts of an upstream library.  As I recall, at the time, recast was still newish, so perhaps we somehow got our hands on a "special" copy?

Does the newer release of recast do something faster/better or newer that we can leverage?  i.e. is there a reason to upgrade, or do you just consider it good form?

**Comment by raptor** [comment]
Good form mostly. 

Also, I'd thought I'd clean up a bit, but I recognized loads of discrepancies:
- Edge detection code was copied/modified and put into the zap codebase
- Recast internal structs have modifications
- Some changes look to be making it 2d from the 3d original
- Several other memory changes in the guts of Recast

So it's more like a `recast-bifighter` package now for some reason. It looks like you, @sam8641, and I all had our fingers in it (week starting about 2011-02-26)

I don't know if anything should be done about it.

**Comment by eykamp** [comment]
> I don't know if anything should be done about it.

Well, do we need to do anything about it :-)  (i.e. could we get improved outcomes by doing something?)

**Comment by raptor** [comment]
Maybe only to avoid being doomed to repeat history...

I was looking again at [Detour/Recast](https://github.com/recastnavigation/recastnavigation) as a full toolkit for AI navigation to support some of these extra features (zone disabling, destructibles, etc.), and which is supposed to perform better than our system (especially the A* part). But I think it would require another crazy large effort with all of us working on it to get it work. It also provides a lot more than we need and I think what we have is sufficient (minus the stuff I'm trying to add now). 

I suspect this was probably our original thinking...

It is nice, however, to not to have to maintain complicated code...

**Comment by raptor** [comment]
This is fixed as of 2705b5c4a3b

Final solution was:
1. Separately mesh zones under Cores and keep track of them
3. In the edge detection algo, set `Neighbor.distTo` to be a high value so A\* could find another way

This allows Cores to still block paths completely if it's the only path while preventing bots from getting stuck if there are other viable paths.

**Comment by eykamp** [comment]
Yay!
