### ISSUE TITLE
Increase number of available loadout presets

### ISSUE THREAD

**Issue by Jomskylark** [bitfighter/bitfighter#659]
Hi, would it be possible to increase the number of available loadout presets? Currently it maxes out at three presets, but I'd really like to add up to five or six total. I use the presets all the time but three rarely seems to be enough, especially on levels with engineer.

If on-screen space is an issue, perhaps only three lines are shown in-game by default, and if a fourth or fifth preset is added in the .ini file then they show up in-game?

Thanks for considering!

**Comment by raptor** [comment]
Yes. Added in 677ca9e
