### ISSUE TITLE
Show defined presets

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#660]
With the number of presets expanded to 6, I think we need a way to show what the defined presets are.  I see two possibilities:

1. Add the info to the help screen that explains how to set/load presets; or
2. Create a sort of informational overlay that shows current presets, when, for example, 0 is pressed (or other key).

The advantage of 1 is that it is unobtrusive and seems to work organizationally.

The advantage of 2 is that it is better integrated into the game.

**Comment by raptor** [comment]
I'm not sure I quite understand. For:
1. Do you mean to add the current users presets to the help screen?
2. `z` then `z` again shows the presets in-game. Did you mean in some other location?
3. 
Also, I'm sorry if I just completed a task you were working on.

**Comment by eykamp** [comment]
I wasn't working on it, no worries there.

1. Yes
2. No, that is exactly what I was suggesting.  Forgot we had it!
