### ISSUE TITLE
A single render call is not in display loop

### ISSUE THREAD

**Issue by fordcars** [bitfighter/bitfighter#664]
`LevelListDisplayer` has a [single render call](https://github.com/bitfighter/bitfighter/blob/master/zap/UIGame.cpp#L3510) out of the main display loop, which could causes issues with some renderer backends. Since `LevelListDisplayer` is already renderer in [GameUserInterface::render()](https://github.com/bitfighter/bitfighter/blob/master/zap/UIGame.cpp#L567), I don't think it's supposed to be there (removing it still displays the level list as far as I can tell).

**Comment by raptor** [comment]
I don't find anything in `git blame` that shows it was added specially. I'd say just remove it and we'll see what happens!

**Comment by fordcars** [comment]
Looks good to me!
