### ISSUE TITLE
Music is just squeaky noise on self-compiled Flatpak

### ISSUE THREAD

**Issue by Mailaender** [bitfighter/bitfighter#666]
**BF version:** 022
**OS/arch:** Tuxedo OS x64

**Describe the bug**
Sound works but music is distorted when I try to run this inside a @flatpak sandbox.

**To Reproduce**
* `git clone https://github.com/Mailaender/flathub/tree/bitfighter`
* `flatpak-builder --user --install --force-clean build-dir org.bitfighter.Bitfighter.yaml`
* `flatpak run org.bitfighter.Bitfighter`

**Log**
> Warning: Big change from first (MPEG version, layer, rate). Frankenstein stream?
[../src/libmpg123/layer1.c:check_balloc():30] error: Illegal bit allocation value.
[../src/libmpg123/layer1.c:INT123_do_layer1():228] error: Aborting layer I decoding after step one.
Note: Illegal Audio-MPEG-Header 0x00ff0000 at offset 52380.
Note: Trying to resync...
Note: Skipped 1024 bytes in input.
[../src/libmpg123/parse.c:wetwork():1365] error: Giving up resync after 1024 bytes - your stream is not nice... (maybe increasing resync limit could help).
Note: Illegal Audio-MPEG-Header 0x0000ff00 at offset 53407.
Note: Trying to resync...
Note: Skipped 1024 bytes in input.
[../src/libmpg123/parse.c:wetwork():1365] error: Giving up resync after 1024 bytes - your stream is not nice... (maybe increasing resync limit could help).
Note: Illegal Audio-MPEG-Header 0x00000000 at offset 54434.
Note: Trying to resync...
Note: Skipped 1024 bytes in input.
[../src/libmpg123/parse.c:wetwork():1365] error: Giving up resync after 1024 bytes - your stream is not nice... (maybe increasing resync limit could help).
Failed to create music stream for av_invis.xm: Unsupported type
Failed to create music stream for feelings.xm: Unsupported type
Failed to create music stream for dreams3.xm: Unsupported type
Failed to create music stream for av_ktb.xm: Unsupported type

**Comment by raptor** [comment]
Hi,

modplug is needed to play those files. Is ALURE compiled with modplug support? Sometimes ALURE falls back to a different codec.

**Comment by Mailaender** [comment]
I tried to reorder dependencies: libmodplug and mpg123 before alure, but that didn't help.

**Comment by raptor** [comment]
We use the option to dynamically load mpg123, but it's never used in-game:

https://github.com/bitfighter/bitfighter/blob/master/alure/CMakeLists.txt#L18

The `-DDYNLOAD_MPG123=1` flag to CMake does this

**Comment by Mailaender** [comment]
> CMake Warning:
  Manually-specified variables were not used by the project:

    DYNLOAD_MPG123

**Comment by Mailaender** [comment]
Ah, I see. Using the in-tree Alure resolves it.
