### ISSUE TITLE
Steam Deck Controllers Work In Standalone AppImage But Not Flatpak

### ISSUE THREAD

**Issue by elementc** [bitfighter/bitfighter#674]
**BF version:** `022`
**OS/arch:** `SteamOS 3.0 Holo / x86-64 / flatpak`

**Describe the bug**
While [the community has been excited to play bitfighter on the Steam Deck](https://discord.com/channels/280140416752549890/325743140059480065/1022393887043633152), the builtin controllers which work fine on the AppImage do not work on the Flatpak version of the game. 

**To Reproduce**
1. Switch your Steam Deck to Desktop mode.
2. Launch KDE Discover, a frontend for Flathub.
3. Install Bitfighter 022.
4. Launch Bitfighter from the Flatpak.
5. Observe that the menu is in keyboard mode only and no Joystick is detected.

**Other**
As I am a novice to Flatpak packaging, I don't have a clear specific pointer to the potential cause, but I suspect some necessary flatpak permission is not specified on @Mailaender 's [flatpak configs?](https://github.com/flathub/org.bitfighter.Bitfighter/blob/master/org.bitfighter.Bitfighter.yaml#L9-L13)

Of note, Heroic Games Launcher [specifies `--device=all` on their configs](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/6db3d19d07f8e2bee6427bd4bb4fa1b4a7ac5725/flatpak/local.heroic.yml#L22) and specifically mentioned that arg on https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1400 where they confirmed the Steam Deck Controllers to be working.

**Comment by eykamp** [comment]
I have none of the hardware nor much of the software to reproduce or test this, but I will make the suggestion that we try using the latest versions of SDL. That is the library that handles all of our controller action, and I did a quick Google search on my phone, and it looks like SDL now supports the Nintendo Switch.

**Comment by elementc** [comment]
> I have none of the hardware nor much of the software to reproduce or test this, but I will make the suggestion that we try using the latest versions of SDL. That is the library that handles all of our controller action, and I did a quick Google search on my phone, and it looks like SDL now supports the Nintendo Switch.

I do not think that the SDL version is implicated given that the same release works just fine on the same device when in appimage format.

I was able to separately reproduce on a generic desktop by running the appimage and verifying it could see my usb xbox controller, but not being able to use the same controller with the flatpak.

FYI, the steam deck is ~ an intel x64 computer running desktop linux, so I think the USB controller on a desktop repro is probably also transferable for @Mailaender in case they also do not have a Steam Deck,

**Comment by eykamp** [comment]
Oops... I somehow transmogrified the steam deck into Nintendo switch in my head.  I've never seen either device in person, but the fact that it runs on the steam deck is pretty awesome.

**Comment by Mailaender** [comment]
https://docs.flatpak.org/en/latest/sandbox-permissions.html#device-access confirms that `--device=all` is required for controllers.

**Comment by elementc** [comment]
Confirmed fix over in the flathub PR!
